### ISSUE TITLE
TigerVNC ends session after 30 seconds with message "Exit request sent."

### ISSUE THREAD

**Issue by grufocom** [asbru-cm/asbru-cm#1020]
**Describe the bug**
Every time I open a VNC session over a SSH jumphost, the session ends 30 seconds later with the message: "Exit request sent."

**To Reproduce**
1. Network settings: set a jump host 
2. connection details: set jour vnc system to connect to
3. connect and wait 30 seconds - session ends

**Expected behavior**
session should stay open until I end it

**Screenshots**
Not a screenshot but this is the text from asbru connection:

TigerVNC-Betrachter (64-bit) Version 1.12.0
Erstellt auf: 2022-07-09 14:10
Copyright (C) 1999-2021 TigerVNC-Team und viele andere (siehe README.rst)
Siehe https://www.tigervnc.org für Informationen zu TigerVNC.

Wed Mar  8 17:37:42 2023
 DecodeManager: Detected 24 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConn:       Verbunden mit Rechner 127.0.0.1, Port 5900
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: Choosing security type VncAuth(2)
 CConn:       Pixelformat depth 24 (32bpp) little-endian rgb888 wird verwendet
 CConn:       Durchsatz 19999 kbit/s - Qualität wird auf 8 geändert
Exit request sent.

DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Wed Mar  8 17:38:23 2023)

**Environment (please complete the following information):**
 - Ubuntu 22.04 ans 22.10
 - asbru v6.4.0

I love asbru connection manager and it make my live a lot easier!
I don't know where those 30 seconds disconnects come from and I hope you have an idea or can help to solve that problem.

Great work!
Manfred

**Comment by grufocom** [comment]
The disconnect of the vnc session depends on the value which is set in "time to connect" in the preferences.
If I set it to the maximum of 100 seconds the connection is stable for 100 seconds and then gets disconnected.
So it seems that asbru-cm does not detect that the connection is active when I use a jumphost!
I Hope this helps to fix that problem.

**Comment by gfrenoy** [comment]
Fyi, not yet a real fix but see #1055, it is now possible to increase "time to connect" above 100 seconds.

**Comment by gfrenoy** [comment]
Ok I found the root cause :-)

When connecting, Ásbrú is waiting for the message `Connected to host a.b.c.d port xyz` but on your German system it displays `Verbunden mit Rechner 127.0.0.1, Port 5900` ; hence Ásbrú believes you are not connected and, after the "connect timeout", it will stop waiting :-/

I made a change to force Ásbrú to use the [C locale](https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do) so that all messages are displayed in English and Ásbrú can correctly detect the connection.

Please test it in the snapshot release and re-open the issue if it should not work for you.

Thanks for the report !
