### ISSUE TITLE
asbru crashes on Opensuse Tumbleweed

### ISSUE THREAD

**Issue by eliwap** [asbru-cm/asbru-cm#1038]
Using version 6.4.0

I've seen similar reports of Asbru crashing on Arch and the fix for that was to downgrade perl-glib-object-introspection to version 0.49-3.

Unfortuneately this is not possible on Tumbleweed without breaking something. The current version available on Tumbleweed is 0.50.

Is there anyway I can work around this? Is a fix coming to allow Asbru to work with newer versions of the required package?

Thanks for any insight anyone can provide.

**Comment by themmm** [comment]
Describe the bug

I am on OpenSUSE Tumbleweed and the Appimage won't start either. Down below are the Logs when trying to start the Appimage:

To Reproduce

- Download Release asbru-cm-6.4.0-1-x86_64.AppImage of Asbru-CM
- Make Appimage executable
- Start absru-cm via console

Environment:

- OS: Opensuse Tumbleweed (latest Updates on 28.06.2023)
- DE: Gnome 44.2
- Kernel: 6.3.7-1-default
- Wayland
- AMD GPU
- Ásbrú Version: 6.4.0.1 Appimage

`sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-bp7pLt/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'

(asbru-cm:26929): Gdk-WARNING **: 15:43:43.876: Failed to load cursor theme Adwaita
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-bp7pLt/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-bp7pLt/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 26929
INFO: Language detected : de_DE.UTF-8, forcing to en_US.UTF-8
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-bp7pLt/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-bp7pLt/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
Argument "" isn't numeric in addition (+) at /tmp/.mount_asbru-bp7pLt/opt/asbru-cm/asbru-cm line 252.
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-bp7pLt/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
Argument "" isn't numeric in addition (+) at /tmp/.mount_asbru-bp7pLt/opt/asbru-cm/asbru-cm line 252.
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-bp7pLt/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
Argument "" isn't numeric in addition (+) at /tmp/.mount_asbru-bp7pLt/opt/asbru-cm/asbru-cm line 252.
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-bp7pLt/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
Argument "" isn't numeric in addition (+) at /tmp/.mount_asbru-bp7pLt/opt/asbru-cm/asbru-cm line 252.
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-bp7pLt/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
Argument "" isn't numeric in addition (+) at /tmp/.mount_asbru-bp7pLt/opt/asbru-cm/asbru-cm line 252.
INFO: Desktop environment detected : other
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-bp7pLt/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-bp7pLt/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-bp7pLt/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-bp7pLt/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-bp7pLt/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
INFO: Config directory is '/home/timo/.config/asbru'
Can't get tcp echo port by name at /tmp/.mount_asbru-bp7pLt/opt/asbru-cm/lib/PACMain.pm line 173.`

Any Help would be greatly appreciated.

Thank you
themmm

**Comment by Stasky745** [comment]
I get the exam same `tcp` error:

```
$ asbru-cm 
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 5411
INFO: Language detected : en_GB.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : other
INFO: Config directory is '/home/stasky/.config/asbru'
Can't get tcp echo port by name at /tmp/.mount_asbru-BUwQXR/opt/asbru-cm/lib/PACMain.pm line 173.
```

Any ideas on how to get it running?

**Comment by marcogiorgio** [comment]
Same problem here using OpenSUSE Tumbleweed 20230709 :cry:

**Comment by gfrenoy** [comment]
Line 173 in PACMain.pm is this:

```
    $self->{_PING} = Net::Ping->new('tcp');
    $self->{_PING}->tcp_service_check(1);
```

Can one reproduce the issue outside Ásbrú ?

To do so, simply create a text file `test-net-ping.pm` containing:

```
use Net::Ping;

$ping = Net::Ping->new('tcp');
$ping->tcp_service_check(1);

printf("All done.\n");
```

And run it from the command line:
```
perl test-net-ping.pm
```

It should display "All done." and no other error message.

If this small test script also fails on your environment, let's [open an issue](https://github.com/rurban/Net-Ping) in to the [Net::Ping project](https://perldoc.perl.org/Net::Ping) to find more appropriate help and suggestion.

**Comment by Stasky745** [comment]
This works fine for me, Shows "All done."

**Comment by gfrenoy** [comment]
> WARNING **: Failed to load shared library 'libayatana-appindicator3.so.1' referenced by the typelib: Error relocating /lib/libayatana-ido3-0.4.so.0: g_time_zone_new_identifier: symbol not found at /tmp/.mount_asbru-EIbn5L/usr/local/lib/perl5/site_perl/Glib/Object/Introspection.pm line 110.

Looks to be a missing dependency in the AppImage... Maybe a dependency to add in [AppRun](https://github.com/asbru-cm/asbru-cm/blob/master/dist/appimage-raw/Dockerfile) ?  I'm not very comfortable with this.

@henry701, would you have any advice ?

**Comment by henry701** [comment]
> > WARNING **: Failed to load shared library 'libayatana-appindicator3.so.1' referenced by the typelib: Error relocating /lib/libayatana-ido3-0.4.so.0: g_time_zone_new_identifier: symbol not found at /tmp/.mount_asbru-EIbn5L/usr/local/lib/perl5/site_perl/Glib/Object/Introspection.pm line 110.
> 
> Looks to be a missing dependency in the AppImage... Maybe a dependency to add in [AppRun](https://github.com/asbru-cm/asbru-cm/blob/master/dist/appimage-raw/Dockerfile) ? I'm not very comfortable with this.
> 
> @henry701, would you have any advice ?

Looks like a symbol relocation issue, but I have to investigate. I'll try to reproduce this and investigate it. This probably slipped because the AppImage wasn't tested with the Unity desktop environment, but only with no environment or GNOME environments instead.

**Comment by henry701** [comment]
Yeah nah it seems we're just missing `libayatana-appindicator3`, because the application assumes it would be accessible when the desktop environment is Unity but this isn't the case when using an AppImage.

We should either add the library (could still cause some issues if the versions from the user's desktop differ) or revert back to using the base system's library path as the last searchable path (causes its own host of compatibility issues, but would solve this one).

I recall searching for solutions to this dilemma when building the AppImage implementation, but this is a complicated one because it's for something deeply integrated with the user's desktop.

Alpine Linux (which is used for building the AppImage using Docker) [does have it in the APK Repository](https://pkgs.alpinelinux.org/package/edge/community/x86/libayatana-appindicator) under the name `libayatana-appindicator`. Shouldn't be much trouble adding it. Can you do that and we ask for a retest?

Now about the earlier messages, which feature another error (`Can't get tcp echo port by name at /tmp/.mount_asbru-bp7pLt/opt/asbru-cm/lib/PACMain.pm line 173.`) doesn't have very recent updates, the latest version (2.75) is from 2022. Maybe we could try temporarily pinning the version to 2.74 and seeing if that works?

I'll try some of those locally after reproducing the problem here but it might take a while to get to it

**Comment by henry701** [comment]
> This works fine for me, Shows "All done."

@Stasky745 What version of `Net::Ping` is installed in your system? This might help with the investigation.

You can obtain this information by running:

```bash
perl -MNet::Ping -e 'print $Net::Ping::VERSION ."\n";'
```

**Comment by Stasky745** [comment]
My version of `Net::Ping` is `2.74`. 

> Alpine Linux (which is used for building the AppImage using Docker) [does have it in the APK Repository](https://pkgs.alpinelinux.org/package/edge/community/x86/libayatana-appindicator) under the name libayatana-appindicator. Shouldn't be much trouble adding it. Can you do that and we ask for a retest?

I'm on Void, not Alpine. Nonetheless, I have the package manager version of `libayatana-appindicator` installed. I could install the `devel` or `32bit` versions too to try, though.

**Comment by henry701** [comment]
> I'm on Void, not Alpine. Nonetheless, I have the package manager version of `libayatana-appindicator` installed. I have tried installing the `devel` and `32bit` versions too to try, nothing changed.

@Stasky745 Sorry for not making it clear, that part of the response was meant for @gfrenoy. The AppImage doesn't use the libraries installed on your system, it bundles all the libraries, so that doesn't change the situation albeit it could fix it if you use Asbrú from the packages or run it directly from the source.

> My version of `Net::Ping` is `2.74`.

Thanks! I pinned the version to this one in my local tests.


I couldn't reproduce the issues for now, actually ran into some new ones (segfaults...) but I tweaked the dependencies a bit and generated a new AppImage that worked locally, pinning the versions of `Net::Ping` and `perl-glib-object-introspection` to old ones. This is not ideal, but not having reproducible builds also isn't.

@gfrenoy I created a [new branch](https://github.com/henry701/asbru-cm/tree/appimage-update-fix) with the changes in case you want to check it out. If it works for the users I'll open a PR.

@Stasky745, @themmm Can you try using [this AppImage](https://mega.nz/file/MBoHzYbK#Eb_D_MOugIeSPLw34KtkGZ4dEa36PXIjnQ5CQp5lBIU) instead of the released one and see how it goes? Alternatively, if you want to check the source before running you may use the branch I linked above and build it as well.

@eliwap Unfortunately this could be a bug in the dependencies, the Asbrú usage of this library doesn't seem to be complex at all. You could try using the AppImage linked above for now as a workaround, it reads the configs from your user directory so it should be almost seamless unless you're doing custom scripting or customizing Asbrú's source.

You could also install the dependency manually via CPANM, overwriting the one installed by Zypper. This isn't pretty, but it could be a viable workaround. It involves installing some development dependencies because CPANM compiles packages while installing them. If interested, try this:

```bash
sudo zypper install perl-App-cpanminus gcc  gobject-introspection gobject-introspection-devel make
cpanm --notest --install XAOC/Glib-Object-Introspection-0.049.tar.gz
```

Let me know how it goes, people!

**Comment by Stasky745** [comment]
> Can you try using [this AppImage](https://mega.nz/file/MBoHzYbK#Eb_D_MOugIeSPLw34KtkGZ4dEa36PXIjnQ5CQp5lBIU) instead of the released one

This one works for me! Haven't tried it too much but at least the program starts.

**Comment by henry701** [comment]
That's the same error on the ping module at the end (ignoring the rest), that's odd.

I'll probably take some time to solve this because it's hard to reproduce. Can you give more detailed system specs? It's an OpenSUSE Tumbleweed installation on bare metal, right? I can try running it inside a VM later, once reproduced I can work on solving it, but it will take some time as I'm currently busy :/. Open another issue, tag me, and reference this issue, please.
