### ISSUE TITLE
Special characters in `expect` for matching Bash prompts

### ISSUE THREAD

**Issue by rudolfbyker** [asbru-cm/asbru-cm#1086]
**Is your feature request related to a problem? Please describe.**

I'm trying to match a bash prompt like `user@host:~$` but special characters like `:` and `~` and `$` don't seem to work in the `expect` field. It never matches.

**Describe the solution you'd like**

I would expect this regex to work: `\w+@\w+:~\$`.

See https://regex101.com/r/HbZSxK/1

![image](https://github.com/asbru-cm/asbru-cm/assets/10025342/c7771a7d-a069-4511-864e-a5e56832286a)

**Describe alternatives you've considered**

This is what I'm using instead, but it's not ideal: `\w+@\w+.{3}`

**Comment by gfrenoy** [comment]
Can you check the "DEBUG expect" option in the Preferences > Terminal Options > Advanced and see if you can spot the exact prompt that is output ?   I would suspect you have other characters in your prompt (like the escape sequences for colors) that might interfere with your regular expression.

In my case `\w@\w` is not match because the actual prompt string is `user\033(B\033[m@\033[33mhostname\033(B\033[m \033[32m~\033(B\033[m\033(B\033[m> \033[K\r\033[20C` ; I have to use `\w.*@.*\w` to match it.

**Comment by gfrenoy** [comment]
Interesting idea :)  Let's close this one for now to stay on the topic.
