### ISSUE TITLE
tab switching / focus issue

### ISSUE THREAD

**Issue by syco** [asbru-cm/asbru-cm#120]
Hi,
I've a minor thing that I'm pretty sure wasn't happening until a few months ago:
When I switch tab I don't use shortcuts, but always click on the tab.
Sometimes when I click on a tab and start typing the terminal doesn't get focused and my typing goes to the info tab.
Did anyone noticed this?

**Comment by gfrenoy** [comment]
Don't see the same behaviour on my machine.  I mean "at all".  Any idea what could be the difference when it "sometimes" happens ?

**Comment by gfrenoy** [comment]
Thanks for the additional information @syco, the problem is very clear.  I did the same as on your video but do not have the same behavior so I guess it is related to a different version of the underlying libraries (like Gtk, Vte, who knows what...).

Can you tell us a bit more about your distribution / environement ?

**Comment by syco** [comment]
Hi,
I'm using kubuntu 18.10, updated from 18.04.
I have to say that it only happen on my desktop, not on my laptop that has exactly the same packages installed and was updated on the same day.

**Comment by gfrenoy** [comment]
Alberto, as we don't have a way to reproduce the issue ; I do fear we'll not able to fix it :-/
