### ISSUE TITLE
Forced password change on logon closes connection

### ISSUE THREAD

**Issue by Hakun1n** [asbru-cm/asbru-cm#138]
**Describe the bug**
When my user password expires on target server i should get a prompt forcing me to change the pwd (classically - enter old, new, new again). Sadly expect messes up this process by sending extra returns (so like no "old pwd' is enterd and the connection is closed). I have to either modify the connection to "manual" or connect outside Asbru, update my password and then it works fine. Doing this for dozen servers is a real pain...

Console:
```
 CONNECTING WITH 'xxxxx' (Thu Mar 21 13:32:26 2019) =->

Offending key for IP in /home/xxxxx/.ssh/known_hosts:1
Matching host key in /home/xxxxx/.ssh/known_hosts:70
Your password has expired. Choose a new password.
WARNING: Your password has expired.
You must change your password now and login again!
Changing password for yyyyy.
Old Password: 
passwd: Authentication failure
Connection to xxxxx closed.

 <-= DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Thu Mar 21 13:32:31 2019)
```
Expect debug attached:
[expect_debug.log](https://github.com/asbru-cm/asbru-cm/files/2992066/expect_debug.log)

See line 72:
`Sending '\n' to spawn id(3)`
Apparently it prompts for Pwd change, it matches on the patter and then it sends a "\n" for whatever reason which prevents me to enter by current password and the new one.

Note that i DONT have any password specified in the connection details. I am using SSH keys.

Thank you in advance for fixing this.

OS + package vers.
Fedora 29 Plasma
perl-Expect-1.35-6.fc29.noarch
asbru-cm-5.1.0~1550941028-1.fc29.noarch
openssh-7.9p1-4.fc29.x86_64
openssh-clients-7.9p1-4.fc29.x86_64
libssh2-1.8.0-8.fc29.x86_64
libssh-0.8.7-1.fc29.x86_64

**Comment by gfrenoy** [comment]
Thanks for the detailed description and log files !  This makes things much easier to analyse and understand :)

So just after line 72, you have line 73, 74 and 75 that are very interesting:

````
 at /usr/share/perl5/vendor_perl/Expect.pm line 1421.
	Expect::print(Expect=GLOB(0x55634ee33828), "\x{a}") called at /usr/share/asbru-cm/lib/pac_conn line 516
	main::send_slow(Expect=GLOB(0x55634ee33828), "\x{a}", "hide") called at /usr/share/asbru-cm/lib/pac_conn line 1434
````

Check line 1434 of pac_conn:

````
  $PASS = subst( $PASS );
  send_slow( $EXP, "$PASS\n", 'hide' );
  $EXP -> log_stdout( 1 );
````

Actually, what happens is that it detects the keyword "password:" and thinks it prompts for your password ... and sends it ; but as you did not define any password in your configuration (what is good, btw), it sends an empty password terminated by a "\n".

So what we need to do is to change the "password prompt" so that it still detects a "Password" prompt but does detect "Old password:" as a password prompt :100: 
![image](https://user-images.githubusercontent.com/981546/54789992-c1815600-4c34-11e9-8db6-582a1d5d9bc5.png)

As you don't use any password, a dirty workaround for you would be to clean that field completely but I don't see immediately how to change the regular expression to fix this.

Any additional idea / contribution will be warmly welcome !

**Comment by Hakun1n** [comment]
Sadly removing the Password regexp does not work either. It still matches on <something>.

`spawn id(3): list of patterns:
  #2: -eof `'
  #3: -re `\\[__PAC__SUDO__PROMPT__\\]'
  #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'
  #5: -re `.*(any key to continue|tecla para continuar).*'
  #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'
  #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'
  #8: -re `'
  #9: -re `[#%\\$>]|\\:\\/\\s*$'

spawn id(3): Does `'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `'? YES!!
    Before match string: `'
    Match string: `'
    After match string: `'
    Matchlist: ()
Calling hook CODE(0x558eced6c448)...
Sending '\n' to spawn id(3)
 at /usr/share/perl5/vendor_perl/Expect.pm line 1421.
	Expect::print(Expect=GLOB(0x558ecdf0b828), "\x{a}") called at /usr/share/asbru-cm/lib/pac_conn line 516
	main::send_slow(Expect=GLOB(0x558ecdf0b828), "\x{a}", "hide") called at /usr/share/asbru-cm/lib/pac_conn line 1434
	main::__ANON__(Expect=GLOB(0x558ecdf0b828)) called at /usr/share/perl5/vendor_perl/Expect.pm line 825
	Expect::_multi_expect(40, ARRAY(0x558eced6caa8), ARRAY(0x558eced68ba0)) called at /usr/share/perl5/vendor_perl/Expect.pm line 602
	Expect::expect(Expect=GLOB(0x558ecdf0b828), 40, ARRAY(0x558eced660c0), ARRAY(0x558eced66558), ARRAY(0x558eced66ca8), ARRAY(0x558eced6bdb8), ARRAY(0x558eced6be90), ARRAY(0x558eced6c298), ...) called at /usr/share/asbru-cm/lib/pac_conn line 1571
[pac_conn(556)][yyyyy][aaaaa]: PASSWORD:Sent (not shown)
Continuing expect, restarting timeout...

spawn id(3): Does `'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `'? YES!!
    Before match string: `'
    Match string: `'
    After match string: `'
    Matchlist: ()
Calling hook CODE(0x558eced6c448)...
[pac_conn(556)][yyyyy][aaaaa]: CLOSE:PASSWORD:Provided username/password 'xxxxx/<<hidden_password>>' was rejected
[pac_conn(556)][yyyyy][aaaaa]: DISCONNECTING
`

**Comment by gfrenoy** [comment]
> Technically it should not match the pattern

I would also think so.

Is there any way for me to reproduce the issue ?  So I can try on my side...

**Comment by Hakun1n** [comment]
Well i guess you should be able to reproduce it by simply running SSH server on a linux. Maybe even local one might be sufficient - just create second user. Generate ssh keys and try to logon with that key (i guess ssh testuser@127.0.0.1 should do the trick). You should get password-less logon just fine. Then make the testuser password expired. Something like "chage -E 2019-03-23 testuser" should do the trick. Then try to logon again with the key. In theory you should be able to logon but get a forced pwd change like me.

**Comment by gfrenoy** [comment]
Thanks for the additional information.  I gave it a try but do not get the same:

```
 CONNECTING WITH 'test3 - tests' (Fri Mar 29 22:49:38 2019) =->

Your account has expired; please contact your system administrator
Connection closed by 192.168.123.204 port 22

 <-= DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Fri Mar 29 22:49:39 2019)
```

After a few more searches, I found out that the following would do it:

```
sudo passwd -e testuser
```

So I could experiment a bit more and found out the following:

- Changing the password prompt does not work as expected ; it does not prompt for anything
- When you need to change the password, if I switch back to the "User / Password" authentication and change a bit the code (see below), I've been able to change the password
- Did not yet find a way to detect the password change when you are in the "Private key" authentication mode.  Maybe it would be OK to change the authentication mode if this should happen ?

The code change I tried:
![image](https://user-images.githubusercontent.com/981546/55266462-60353480-527d-11e9-8e01-a42a6f36a8ef.png)

**Comment by jacekciach** [comment]
@Hakun1n @gfrenoy Please try a regexp (I don't have a possibility to check it in Asbru in the moment, but I've  verified the regexp on regex101.com)
```
(?<!([o|O]ld|[n|N]ew) )([p|P]ass|[p|P]ass[w|W]or[d|t](\s+for\s+|\w+@\w+)*|[c|C]ontrase.a|Enter passphrase for key )\s*:\s*$
```
The modified regexp uses "negative lookbehind" (notice the part added at the beginning of the original regexp)
https://regex101.com/r/9ntUot/2

In order to better understand what's going on - there is a simpler example:
https://regex101.com/r/dBx0mg/1

I'm aware that it may not be perfect (not cover all possibilities / cases), but surely does the job with @Hakun1n 's example.

Please give me a feedback, if my solution works in Asbru.

**Comment by gfrenoy** [comment]
@jacekciach Thanks for the suggestion but I do fear it is not working since we do not want to exclude the password match but to make sure it triggers a "ask password" action...

I played a bit more with this.  I think I have now something that is correctly catching password prompts in various scenarios.

The next commit  shall fix this issue, testers are welcome !

@Hakun1n let us know if it works for you.
