### ISSUE TITLE
Cant start SSH session since last update (missing PACUtils.pm) on Fedora

### ISSUE THREAD

**Issue by Frankstar** [asbru-cm/asbru-cm#147]
**Describe the bug**
Installed version: `Package asbru-cm-5.2.1~1557648821-1.fc28.noarch`
Im on Fedora 30, it worked flawlessly.
i saw an update yesterday and since than i get
 
```
Can't locate PACUtils.pm in @INC (you may need to install the PACUtils module) (@INC contains: /usr/share/asbru-cm /usr/share/asbru-cm/lib/ex /usr/share/asbru-cm/lib/edit /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /usr/share/asbru-cm/lib/pac_conn line 42.
BEGIN failed--compilation aborted at /usr/share/asbru-cm/lib/pac_conn line 42.
```

**Comment by gfrenoy** [comment]
This has certainly been introduced with https://github.com/asbru-cm/asbru-cm/commit/8d13cbab824068c9b90a111742dd63eedc77aaab#diff-b066df855295868fcdd728ab78960236 but at this stage I cannot understand why since it works for me (on Ubuntu 18.04).

I'll need give to give it a try on a fresh F30 install.

If you need a quick fix, simply revert the changes at lines 42 and 50 in pac_conn.

**Comment by Frankstar** [comment]
yes reverting this fix the issue.

**Comment by Mjolinir** [comment]
I can confirm this behaviour on Fedora 30 also. It also does not allow ssh connections. It still works fine in ArchLinux.

**Comment by gfrenoy** [comment]
Found out that the include path is "crafted" when the RPM is built and, if I got it correctly, the search/replace that was done was not correct.  I just fixed it know...

Can you give it another try ?
