### ISSUE TITLE
"Start > n instances" usually does nothing.

### ISSUE THREAD

**Issue by clickwir** [asbru-cm/asbru-cm#16]
I haven't found a reason why, but usually starting 'n instances' does nothing. Sometimes, for the same connection, it works fine.

For one connection, I tried starting 2 instances 10 times. Out of those 10 times, it worked 1 time. Another connection, worked 3 out of 5 times. Another connection, haven't been able to get it to work at all (probably tried 30+ times).

All my connections are pretty simple SSH connections that have a user/pass saved. All of them work fine if I double click them. They connect and login.

**Comment by gfrenoy** [comment]
Thanks for the info.  I do confirm.  It does not work for me neither... 

I'll try to troubleshoot this further to collect more information.

**Comment by gfrenoy** [comment]
What I found out so far is that the action is correctly triggered if you do it from the keyboard.  But if you are using only the mouse, the event looks to be ignored.

To be continued.

**Comment by gfrenoy** [comment]
Found another "trick".  If you explicitly click on "Start" to expand the submenu, it works every time (even with the mouse).  But if you only "hover" on "Start" (what will also popup the submenu), then the click on the "n instances" will be ignored...

Mmm...?

**Comment by clickwir** [comment]
Yup. Confirmed. Even if the menu auto expands, clicking on Start and then on an instances option works each time. 

I didn't notice that before, I must have clicked on it a few times before and saw it work sometimes.

**Comment by merikz** [comment]
Looks like this one
https://stackoverflow.com/questions/5221326/submenu-item-does-not-call-function-with-working-solution
which points to this open (since 4 years) bug on gtk:
https://bugzilla.gnome.org/show_bug.cgi?id=695488

It says that sub menu items don't get a callback when they are clicked, unless the parent menu item has been clicked before. Pretty much exactly the problem we have.
There is a workaround in the first link. Seems pretty complicated, though. 
Wonder if the reason for not solving it in gtk has something to do with gtk3? How's the asbru GTK3 branch going? Is it possible to test this there?

**Comment by gfrenoy** [comment]
Thanks for the additional information Magnus, I was suspecting it was a problem in Gtk but did not find the reference !  Great finding :-)  I checked how we hook the function (see _wPopUpMenu in PACUtils.pm) and the workaround is really not obvious to integrate.

I would suggest to close this as "won't fix" since we can indeed reasonably think it will be fixed in Gtk3.

Btw, you'll find the progress of the migration there : https://github.com/asbru-cm/asbru-cm/projects/1
But trees are not working yet so I cannot tell you for sure that it'll be fixed...
