### ISSUE TITLE
Deleting one cluster deletes all

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#180]
1. Click on "Clusters" (bottom left).

2. Click on "Add". Type "asdf" as a new name for this cluster into the popup window.

3. Repeat with "qwer", "zxcv" and so on.

4. The "Active Clusters:" combobox has all these entries you just added. Pick one, let's say "qwer".

5. Click on Delete. Confirm the question "Delete cluster 'qwer'?"

6. Notice that all the entries are gone, not just "qwer".

I have to admit I have no idea what I'm doing, what this UI is for, but I'm pretty sure that asking for confirmation to delete one and then deleting all of them is not okay.

This is with current master (gtk2).

**Comment by gfrenoy** [comment]
Very confusing indeed.  Not sure why David did like that.
Not even sure if someone is really using this kind of feature and how...

If anyone wants to have a look, any kind of help will be appreciated.

**Comment by hanspr** [comment]
The code ignores all clusters that are empty (no terminals in the cluster). Every time it saves its configuration.

If you do the same exercise, and do not delete anything. But close the window and reopen, all the empty clusters were not saved.

If you create your clusters, and then add terminals to it.

The cluster will be saved and if you delete a cluster, that cluster will be deleted and that one alone correctly.

So, it depends on what behaviour should we implement. Allow to create and save empty clusters or add a warning that all empty clusters will be discarded.

**Comment by gfrenoy** [comment]
On one hand, I find that "cluster" option very interesting ; on the other hand, the current implementation is so confusing that I suspect only a few nerds is really using it.

So if we can have clear way of managing clusters, I'm sure we can convince that few users to move to the "right" way of managing this.

Having said that, I don't have a "spec" for the "right way" :-)

So let's take this as a "brainstorming" session...

1) The right part of the screen (running / active / auto) looks to be the first step of the reasoning so I don't understand why it's on the right side of the window
2) Persistence is indeed not very intuitive
3) Saved clusters seem useless
4) What means "auto" ?

So, all in all, my thoughts tonight are:
- only keep the "saved" concept
- simplify the UI
- can we merge "Clusters" and "PCC" ?

**Comment by hanspr** [comment]
Merge Clusters and PCC: no, Clusters is to manage, and PCC is to interact, and is small so it does not interfere with the terminals. If we touch PCC, should be to make it even smaller.

**Auto clusters**. I think the concept is to add regular expressions to title, description, etc. And then have a cluster that when you start it, it will look for all terminals that match the conditions and opens them as a cluster. Instead of creating a cluster and attach terminals to it (Saved clusters option). It feels over sophisticated (unless you are one of those persons that needs to open 40 terminals in a cluster and do not want to associate the 40 terminals one by one to a cluster).

**Running** I do not see the usefulness of this.

We could remove running clusters and show always saved clusters as the first default option.

I do not see any harm on leaving Auto clusters if we document to the user how it works and use it if they really find it useful, the code is already there. But if you think we should remove it, I would not mind.

If you agree I could try to give it a shot and see if I learn some Gtk interaction on the way.
I will have a very busy week, so I don't think I could deliver something until next Monday.

**Comment by hanspr** [comment]
I did a quick test,

Deleting the extra code has been hard, would need to study it a lot.

Tweaking it, well I managed to hide the elements and reorder them to make it look like this.

![imagen](https://user-images.githubusercontent.com/1572396/67349681-42c40280-f50e-11e9-9769-3cbb0cfbba7a.png)

Or like this, if you want to preserve the Auto Cluster

![imagen](https://user-images.githubusercontent.com/1572396/67349693-49eb1080-f50e-11e9-9df5-ef9d02789e47.png)

At least looks simpler.

Regarding saving empty clusters, the problem is that right now the algorithm deletes the combo box and then reloads the saved clusters from the config file. Actually if you have a cluster with terminals and begin removing, because it saves the configuration after each deleted terminal, when you remove the last terminal from the cluster, the cluster disappears from the combo box immediately.

**Comment by gfrenoy** [comment]
The dialog looks indeed much more simple :)

But I still don't really understand how to use it :-/

So I created a cluster with two similar machines ; exactly as you did.  How do you use it in PCC ?

**Comment by hanspr** [comment]
To create a cluster

Add name

![imagen](https://user-images.githubusercontent.com/1572396/67621669-81d8a900-f7d7-11e9-9587-140c838d9f0f.png)

Select terminals from the left and add them the the add to cluster button

![imagen](https://user-images.githubusercontent.com/1572396/67621672-8ac97a80-f7d7-11e9-9508-3fbdcbf6df83.png)

When done selecting, click the Add button to save changes

![imagen](https://user-images.githubusercontent.com/1572396/67621678-a2086800-f7d7-11e9-996a-39692b22c9fc.png)

The new cluster will be available in the menu or the cluster list on the main window

![imagen](https://user-images.githubusercontent.com/1572396/67621680-b5b3ce80-f7d7-11e9-85c3-54b9726d5447.png)

![imagen](https://user-images.githubusercontent.com/1572396/67621685-c5cbae00-f7d7-11e9-8946-010a863ccf57.png)

Click on the cluster menu, or double click on the cluster list

This will open all terminals simultaneously and link the keyboard to all terminals in the cluster

So anything you write on one will be simultaneously typed in the others

![imagen](https://user-images.githubusercontent.com/1572396/67621699-fa3f6a00-f7d7-11e9-8bca-1cdde9285516.png)

This is more an admin tool than programmers, you can use it to type common commands to servers that are very similar o identical, this allows to :

* update several servers
* edit a config file on all of them at the same time
* I program remote raspeberri Pi that are connected to electronic scales, etc. And have very unique code that is similar across them but I do not have a development environment because I do not have the interest in buying expensive scales or robot arms, to yus be able to develop. So I connect to all of them simultaneously, they all have exactly the same code and I edit the code on one terminal and I'm patching on real time the others. Of course I could work on one and then copy the file to the others, but for small adjustments this has been always more practical.
* and there are some other more complicated uses when add to the terminals tunnels, expect, etc. All those tunnels will open simultaneously too.

The PCC, is used on 2 conditions.

* You open several terminals that have no cluster
  * So you open the PCC and activate, send keys to all open terminals, similar, but terminals are not clustered
  * Open a cluster and for some reason you loose communication with one of them and that terminal reconnects but is no longer with the cluster.
* Its main advantage is that you can type a command on a single terminal and is not passed to the others, you use the PCC to pass it to all. With a cluster you can not type a different command on one of them they are tied together.

Those are the basic principles, I think the Running terminals managemente lets you cluster and uncluster terminals that are running, but have never used it.

**Comment by gfrenoy** [comment]
Waw!  Thanks a lot :)

I never used that feature and actually never saw I can start a connection from the icon in the top bar !

Let me create a wiki page about this !

**Comment by hanspr** [comment]
I think this issue should be closed and clear the board.
