### ISSUE TITLE
starting asbru-cm a second time leads to segfault

### ISSUE THREAD

**Issue by yennor** [asbru-cm/asbru-cm#23]
If asbru-cm is already open and I forget that, and want to start it again, the previous instance of asbru gets segfaulted and I end up with none instance at all.
Segfault:
asbru[1407]: segfault at 300f0b00 ip 00007fd40f62e646 sp 00007ffd1ced7d78 error 4 in libc-2.24.so[7fd40f5ae000+195000]

This is on a debian stretch.

**Comment by gfrenoy** [comment]
Thanks for the report yennor.  I do see the same on Debian Strecth.  But not on Ubuntu Xenial.

From what I see so far:
 - when the second instance is starting, it sends a signal to the first one
 - upon reception of that signal, the first instance crashes (without any clear reason) !

The issue seems to happen in Gtk...

**Comment by hanspr** [comment]
Hi @yennor 

The past few months we have been dedicating a lot of time to upgrade to gtk3. The branch is very stable and I have not seen any crashes of this type.

Hope you could test the gtk3 branch and tell us if this bug is still there or maybe with all the changes we have made has been removed.

To test the gkt3 branch, install asbru from the instruction pages at : [https://github.com/asbru-cm/asbru-cm/tree/gtk3](https://github.com/asbru-cm/asbru-cm/tree/gtk3)

Or clone the branch and install dependencies, what you consider easier.

Thanks, for your help.
