### ISSUE TITLE
Double click on tab to restart

### ISSUE THREAD

**Issue by figue** [asbru-cm/asbru-cm#281]
**Is your feature request related to a problem? Please describe.**
Sometimes when a RDP tab reaches a timeout, session is disconnected. Right click to clone connection is a direct workaround, but a "restart" or "reconnect" function will be better.

**Describe the solution you'd like**
Double click on tab button to restart

**Describe alternatives you've considered**
If double click can't be implemented, maybe a combination of Control+left click or something like that.

**Comment by egmontkob** [comment]
My 2 cents: If this feature is desired, let's rather have an entry in the right-click menu.

Double click or Ctrl+click are hard to discover. An entry in the right-click menu is easy to.

Also it's probably unexpected for double click to have any effect, especially a destructive one (closing the existing connection). I can't recall ever seeing a UI where double clicking on a tab bar has such an action. The expected behavior is to do nothing (maybe the user just clicks through the tabs while bored, waiting for some other action to complete, and accidentally clicks twice quickly over the same tab), or maybe something non-destructive such as editing the tab label.

**Comment by figue** [comment]
A menu option is ok too. Maybe double click to reconnect can be only in disconnected RDP/ssh tabs. 
There is another program for Windows that works this way (if it's connected double click put full screen, and if it's disconnected connection is restarted).

**Comment by gfrenoy** [comment]
Interestingly there is a "Restart session" option for SSH terminals:
![image](https://user-images.githubusercontent.com/981546/69495822-950c9080-0ecb-11ea-8cab-32566e278f56.png)

As a first step, I'll add this same option when you right click the terminal tab.

We now need to be sure the RDP connection is properly restarted.

**Comment by gfrenoy** [comment]
The "Restart session" option is now available and seems to work.  Additional testers on the [gtk3 branch](https://github.com/asbru-cm/asbru-cm/tree/gtk3) are warmly welcome :)

Moreover, as the VTE terminal will now be displayed whenver the RDP connection is lost, simply hitting "ENTER" will also establish the connection again.  Just as it works for SSH connections, basically.

Let us know if works better for you (or not...).

**Comment by figue** [comment]
Thank you for the big update you push today. Hitting ENTER reconnects RDP just fine. Good job with Ásbrú
