### ISSUE TITLE
Resizing left menu section doesn't repaint the console properly

### ISSUE THREAD

**Issue by ferent** [asbru-cm/asbru-cm#310]
**Describe the bug**
Resizing left menu section where the Connections are listed doesn't repaint the local console properly, see image attached

**To Reproduce**
1. With a local console open, resize the left menu a few times

**Expected behavior**
To repaint the console leaving the content as it was.

**Screenshots**
![Screenshot from 2019-12-13 14-47-50](https://user-images.githubusercontent.com/1398552/70808464-a6083d80-1db7-11ea-8a73-b84c2e641afe.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04
- Shell ZSH

**Comment by gfrenoy** [comment]
Thanks for your feedback.  Do you observe the same with another shell ?  Or is this specific to ZSH ?

As a matter of fast, I don't use ZSH and cannot reproduce this issue :-/

**Comment by egmontkob** [comment]
It's how VTE's rewrapping of the lines interferes with the shell redrawing its prompt. You should ask the shell's (in this case: zsh's) developers to add support for terminals that rewrap their contents.

**Comment by gfrenoy** [comment]
Thanks for your help @egmontkob !

So at this stage, I would assume there's anything we can do on our side...

I guess this has already been reported to the ZSH project ?  I searched a bit but did not find the best place to report the issue ... Would you have an advise ?

**Comment by egmontkob** [comment]
> I guess this has already been reported to the ZSH project ?

I don't know.

VTE has been rewrapping its contents for 6 years now. Some terminals for even longer time. Some others joined the game since then. I'm pretty certain that rewrapping terminals are used more often than non-rewrapping ones. [This is not an out-of-the-blue wild guess. It's based on [this poll from 2017](https://opensource.com/life/17/10/top-terminal-emulators) where VTE-based terminals received somewhere between 55% - 70%; other sources (e.g. Debian popcon) suggesting similar numbers; plus both popular macOS terminals rewrap (the default Terminal.app and iTerm2); and there are newly appeared rewrapping terminals such as Kitty or Windows Terminal.]

Still, shells (at least bash and zsh) assume that the terminal does not wrap their contents, and I'm not aware of a config option to expect that the terminal rewraps.

I've come across this issue reported many times for terminals (including terminal bugtrackers, as well as various forums). In quite a few of them it was pointed out that shells should be adjusted to the new behavior, beucase it's hopeless for terminals to rewrap everything except the last prompt (since they have no clue what a "prompt" is), and they don't want to remove this awesome feature of rewrapping.

So I would be truly surprised to hear if shell developers weren't aware of this issue. Although maybe they aren't.

**Comment by hanspr** [comment]
That is a zsh "theme" them issue. It rewraps the last line, but not previous ones, I I do not know if it could, in my case I use zsh too and I have done the exercise the asbru and tilix, is the same

Original size,

![imagen](https://user-images.githubusercontent.com/1572396/71126781-53f85b00-21af-11ea-8b05-74609e08553b.png)


After shrink

![imagen](https://user-images.githubusercontent.com/1572396/71126625-fc59ef80-21ae-11ea-9c39-a704214b75d2.png)

Everything resized correctly

But, if you add text, and then resize, the previous lines are not redrawn, but the last one it is.

Asbru

![imagen](https://user-images.githubusercontent.com/1572396/71126607-f6640e80-21ae-11ea-9ca3-30dc2a7d9e73.png)

Tilix

![imagen](https://user-images.githubusercontent.com/1572396/71126956-aa659980-21af-11ea-8ab4-ebc1e1449497.png)

**Comment by gfrenoy** [comment]
Ok so if it's a ZSH issue and if I understand that project correctly (they don't make this easy ;), it should be reported to zsh-workers@zsh.org.

I would some interesting discussions (by searching [on terminal resize](https://duckduckgo.com/?q=terminal+resize+site%3Awww.zsh.org)):
- http://www.zsh.org/mla/users/2004/msg00685.html
- https://www.zsh.org/mla/users/2013/msg00285.html
- http://www.zsh.org/mla/workers/2015/msg00847.html
- https://www.zsh.org/mla/workers/2017/msg01367.html

Not sure of the conclusion though :-/

**Comment by hanspr** [comment]
This should be closed

**Comment by gfrenoy** [comment]
Indeed, as there is nothing more we can do in Ásbrú, this issue is now closed.
