### ISSUE TITLE
Configuration file version

### ISSUE THREAD

**Issue by gfrenoy** [asbru-cm/asbru-cm#353]
**Is your feature request related to a problem? Please describe.**

The current configuration file does not contain any indication about which version of Ásbrú has been used to create it.

**Describe the solution you'd like**

The yml configuration should contain the version of Ásbrú with which it has been saved.

**Additional context**

Any feature change should consider a way to handle the upgrade of the configuration and warn the user that this upgrade will make the file incompatible with a previous version of Ásbrú.

**Comment by merikz** [comment]
Shouldn't this be a configuration version number rather than the asbru version number? 
Otherwise this parameter would change at every release, even if there is no actual change to config file format. That would be a pain to handle when you actually do a configuration change and need to find out if a migrate of the config is necessary.

It's much easier with just an integer.

For user communication we could maintain a translation map between config version and asbru version, so the user only sees asbru versions in any warning messages if needed.
(Maybe it would be convenient also for maintenance to see which asbru version that introduced a specific config version.)

**Comment by hanspr** [comment]
As I might be the first want to require this, my proposal is a bit different.

We should control "patch numbers applied", more than a version number.

So the logic would be:

* Have a utils folder
* Place any patch to apply to the configuration file there
* Patches should be named : YYYYMMDD.pl
* The yml file should have the last patch applied (which should be the latest date), aka the version number
    * Or even better the list of all patches applied
* At startup, asbru should check the existing scripts in the utils directory and if any filename is higher than last patch applied
    * Or better not included in the applied patch list
* Then run the script
    * The script should be simply run by ``` $result = `$ENV{ASBRU_CFG}/utils/20200101.pl config-dir=$ENV{ASBRU_CFG}`; ```
    * script should print "OK" at the end if migration is successful, or an error message and abort at at time.
    * `$result != "OK"`, is an error message and should be displayed to the user and abort loading
    * `if $result == "OK"`, if the process is reported as completed
    * update yml file that patch has been applied
    * Check for more pending patches and redo
* Hopefully this list of scripts should not get too long.

With this logic you can run all the missing patches even if a user jumps from old PAC, to Asbru 10 with 3 patches in the middle. And there is no need to control version numbers but the actual important object that is what has actually been applied to the config file. Or if some one goes from Asbru 7 to Asbru 10 with 2 missing patches in the middle

**Comment by hanspr** [comment]
From my previous comment, some simple additions can be applied to the logic proposed

* Add pod documentation at then end of each script to document : changes applied, what will be modified, incompatibility issues, version in which was introduced, an any other valuable information.
* The summary will be extracted and presented to the user with a simple ``` $info = `perldoc $ENV{ASBRU_CFG}/utils/20200101.pl` ```

**Comment by KlaasT** [comment]
So you are basically speaking of "migration" files as if you were using Laravel (PHP).

**Comment by hanspr** [comment]
Never heard, read about Laravel (PHP), but is no surprise if someone is doing the same logic in other projects.

I've been using this technique to update a software of mine for the last 18 years. That is why I'm proposing it.

**Comment by merikz** [comment]
I agree on the logic, but 
- What is the point of the date in the filenames? What date is it, the date the script was developed? Applied? 
The important point, to me, is that since you know what is the latest version (hard coded in the source code), you must be able to determine which delta to apply by comparing the version stored in the config file. You need to apply all the deltas in between, and they will exist as they are part of the asbru delivery.
  Might just as well be a sequence number as I see it. 
- Why different files? They would be part of asbru, right? So why not stick to the way we already use, one file for one 'thing',  so this could be in a PACConfigMigration.pm and handle all of it. Instead of a bunch of files, make a bunch of functions. 
Would you ever run these migrations stand-alone?
 This is not a variation point where the user can modify the content of the configuration. It is all about the format of the configuration.
- What should happen at failure? We migrate because the config is not compatible with the code, so if migration fails we cannot start asbru. So we need to start with making a backup copy, and at failure tell the user he need to downgrade to previous asbru version and restore the config from backup.

**Comment by hanspr** [comment]
>What is the point of the date in the filenames? What date is it, the date the script was developed? Applied?

Developed, easy comparison

>The important point, to me, is that since you know what is the latest version (hard coded in the source code)

That is the point, we will not need anything hardcoded

>Why different files? They would be part of asbru, right?

Happen in different times, yes but is not worth to have it inside permanently, the patch should be applied once in a life time and then ignored, without having to carry a lot of code inside the application

>What should happen at failure? We migrate because the config is not compatible with the code, so if migration fails we cannot start asbru. 

That would depend on the script informing if it is save to start or not Asbru with the kind of failure it had.

Testing of this things is always essential.

But again, is a proposal, don't like it, propose something.

**Comment by hanspr** [comment]
Added stamp for file version on PR #515 

Set it to `1.0.0`

If this is all that you planed for this request as you explained to me, then this should be closed.

**Comment by gfrenoy** [comment]
I would make it even simpler and use only one non-zero strictly increasing integer (1, 2,3, ...).  Was also the merikz' suggestion, btw.

If we ever make a change that requires some changes in the configuration file : that's enough to check from where we start and what to do, isn't it ?

And at this stage, I indeed don't see any migration script(s) to prepare.  This step is only a preparation for them, if ever needed.

Thanks!

**Comment by hanspr** [comment]
Reset to `1`

**Comment by gfrenoy** [comment]
Ready in loki.
