### ISSUE TITLE
Some servers disconnected when using clusters

### ISSUE THREAD

**Issue by smikanl** [asbru-cm/asbru-cm#373]
Hi,

Thanks for the great software! When I want to login on multiple servers when using clusters (say 15 - 25 servers at once), then most of the servers are connection correctly the first time. Some of the servers are disconnected and I need to reconnect them manually. Is there a possibility that when a server is disconnected when connected the firstime, it will try again? I think this issue occurs when connecting to too much servers at one.

Smikanl

**Comment by hanspr** [comment]
Have you tried this feature on those servers?

![imagen](https://user-images.githubusercontent.com/1572396/72831163-e88b2880-3c47-11ea-862d-3a13fe22cd5f.png)

Test this feature to see how it works.

What I'm not sure is if it is possible to tell the difference between a timeout and a real network or server failure (network or server down), and if we should limit the retries, have not checked that part of the code.

**Comment by smikanl** [comment]
Thanks for your reply. Thanks for the tip, but i doens't work. Maybe in a future release there be a repeat option when the connection isn't accomplished the first time.

**Comment by hanspr** [comment]
Ha !, How embarrassing, that chekbox option has no code to handle a reconnection in Ásbrü.

**Comment by hanspr** [comment]
Wrong, it does, let take a look. And see why is not working.

**Comment by smikanl** [comment]
I see that you fixed it. How can I implement this update? Just update PACTeriminal.pm?

https://github.com/asbru-cm/asbru-cm/pull/377/commits/44f5469308d8dd891d753d73b0804c8aff8699e8#diff-38f0f2a16f32b7fac67beb95aa89ac9b

**Comment by KlaasT** [comment]
I can try to Backport the fix later this day. So can use a snapshot from master

**Comment by hanspr** [comment]
Give a few minutes and send it to master, is 2 files PACTermina and pac_conn

**Comment by KlaasT** [comment]
Merged into master. The snapshot builds are being created right now.

**Comment by smikanl** [comment]
I tested today your code, but it works only for the first server. Here is an explanation:

I connect to 16 servers

the first 5 servers are connected right away.
The 6th one can;t connect the first time so it will try 4 more times.
The 7th until the 9th, are connected right away
The 10 is not connected, but will not try it 4 times!
The rest is connected right way.

So only the first not connected will retry 4 times, but not the other 1,2,3,4 etc. servers.

Hopefully you understand my question.

smikanl

**Comment by hanspr** [comment]
Hi  @smikanl 

I can not reproduce the problem

![imagen](https://user-images.githubusercontent.com/1572396/73188181-1361fa80-40e8-11ea-88b0-7a01969306a7.png)

To be able to further assist you, we will have to begin debugin and give me more information than just descriptions of the symptoms.

__Warning: This procedure might generate sensitive information__, check the logs you will send, remove anything you do not want to share or we will have to find out a way to cross information and debug this issue further. You may locate my personal email in my profile and from there and contact me to figure how to debug this and what options can you provide.

1. Confirm that you have cloned this git and that you cloned the loki branch to test. No manual copying code into your installed application
2. Once you have the loki banch cloned

Close your asbru application

Edit PACTerminal.pm

Find `sub _watchConnectionData` in line 1389

And add `print "$data\n";` around line 1402, similar to the image

![imagen](https://user-images.githubusercontent.com/1572396/73188927-350fb180-40e9-11ea-91c1-32150a75abc0.png)

3. Then you will have to open a terminal in the cloned repo location and run asbru directly in the terminal

![imagen](https://user-images.githubusercontent.com/1572396/73188581-b61a7900-40e8-11ea-9ce9-8adab663181f.png)

4. Test your cluster and send me the print out (as text) similar to this

![imagen](https://user-images.githubusercontent.com/1572396/73189196-9fc0ed00-40e9-11ea-9ac0-b421f6bc6876.png)

If you can test with the least amount of servers it would be better, pick the 3 more trouble some an check if you can reproduce with a cluster of 3 to 5 servers so that listing is not extremely long.

Hopefully, there would be some useful information to understand if the error is different than a timeout, because the retry is only applied to timeout errors, not other kind.

**Comment by hanspr** [comment]
Just to confirm I ran the implementation in the master brach, and it works for me as well.

![imagen](https://user-images.githubusercontent.com/1572396/73190730-0b0bbe80-40ec-11ea-9915-45cd18d41100.png)

You may run the instructions above in the master branch but the routine will be located at different line `1432`

**Comment by hanspr** [comment]
@smikanl 

Sent another PR, hope it works better.

Could you confirm what timeout you have configured in Terminal Options > Behaviour

![imagen](https://user-images.githubusercontent.com/1572396/73385201-5bbd1c00-4292-11ea-8764-0a550f59fd94.png)

And if is 10 or less increase to 15 or 20 to see if it helps?
