### ISSUE TITLE
Focus on connections can change and not be apparent why

### ISSUE THREAD

**Issue by clickwir** [asbru-cm/asbru-cm#38]
Sometimes when going out of either the Edit Connection or Rename Connection window, the highlighted connection would swap. Did it just change the sort order of 2 things that are named the same or did it just flop which one is highlighted for some reason?

That causes me to have to go back in and out of each entry to look at the host IP a couple times to make sure I'm going to "Rename Connection" for the correct one.

**Comment by gfrenoy** [comment]
I made some tests here and noticed that it does strange re-ordering operations after rename or edit.  And it does not look consistent between edit and rename.

But the selected node remained always the same.

Can you identify a case where it does not behave as expected ?  And maybe give a step by step example so that I can reproduce it ?

**Comment by gfrenoy** [comment]
Any additional information you could give to help reproduce the issue ?

**Comment by gfrenoy** [comment]
Closed due to inactivity.  Feel free to re-open if there's anything new.
