### ISSUE TITLE
Loki branch - Auto saving feature

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#437]
Hi Team ...

I do have the "Auto save config changes" unchecked in the Main Preferences.
![image](https://user-images.githubusercontent.com/37672088/75808269-ba3c5500-5d7e-11ea-9edd-54726252f310.png)

Upon Asbru startup, the push button next to the Preferences button, has a grayed out "Save" legend:
![image](https://user-images.githubusercontent.com/37672088/75808455-0a1b1c00-5d7f-11ea-8a62-8e171cd0ff86.png)
 
Whenever I modify and save something in the Main Preferences dialog or in some Node configuration, the button gets updated with a grayed out "Auto saving ACTIVE" legend:
![image](https://user-images.githubusercontent.com/37672088/75808127-7ba69a80-5d7e-11ea-9db4-62b6b257d0fe.png)

Why is the Auto Saving (apparently!) being turned on when I've it off in the Main Preferences ?
May you please explain how this feature is supposed to work ?

Thanks.

**Comment by hanspr** [comment]
Please send an exported configuration to be able to check

Preferencies > Export > DEBUG data

**Comment by popxunga** [comment]
Hi @hanspr 

Just tested it and it happens with a vanilla configuration.
So no need to send the configuration export I guess.

BTW the anonymized export configuration needs improvement (more configuration fields needs to be anonymized). 

Thanks.

**Comment by gfrenoy** [comment]
First, the theory: "Auto save config changes" inside the "At exit" section means that any change will be automatically saved when you exit the software.

Now, in practice, when you have "Automatically save every configuration change" checked, it does not really make sense to have this other option since all changes are immediately saved so, for sure, when exiting, whatever you chose, there's nothing more to save.

When you see "Auto saving ACTIVE", it's actually related to the other parameter on the same panel ("Automatically save every configuration change").

From here, I have some more questions to brainstorm this further:

- Should we hide "At exit" > "Auto save config changes" when "Automatically save every configuration change" is checked ?
- Should we change the text / tool tip to make it clearer ?
- Any other thought ?

**Comment by hanspr** [comment]
@popxunga 

>BTW the anonymized export configuration needs improvement (more configuration fields needs to be anonymized).

Could you open a new issue pointing the fields that you have detected that need to be anonymized?

**Comment by popxunga** [comment]
Hi @gfrenoy 
I didn't notice the other option "Automatically save every configuration change".
My suggestion is automatically uncheck and gray out the "Auto save config changes"  option whenever the "Automatically save every configuration change" option is checked.
Thanks.

**Comment by popxunga** [comment]
> @popxunga
> 
> > BTW the anonymized export configuration needs improvement (more configuration fields needs to be anonymized).
> 
> Could you open a new issue pointing the fields that you have detected that need to be anonymized?

[Here](https://github.com/asbru-cm/asbru-cm/issues/439)
Thanks !

**Comment by gfrenoy** [comment]
We made some changes to the preferences panel ; let us know if this makes things clearer.

**Comment by popxunga** [comment]
> We made some changes to the preferences panel ; let us know if this makes things clearer.

Hi @gfrenoy 
I think its better now.
Thanks !

**Comment by gfrenoy** [comment]
Cool !  Should we consider this closed ?

**Comment by popxunga** [comment]
Hi @gfrenoy ...
Yes.. I guess we can ;-)
Maybe in the future we should consider grouping the Preferences settings in some tabs within some rectangles... sometimes the disposition looks a bit fuzzy which makes reading a bit difficult. 
Thanks.

**Comment by gfrenoy** [comment]
Yes, a lot of work on UI/UX ; that goes far beyond the current issue.  Let's close this for now.  Thanks for the valuable feedback !
