### ISSUE TITLE
Auto-save by default

### ISSUE THREAD

**Issue by cambohost** [asbru-cm/asbru-cm#44]
Not really an issue per-se, however by default the "Save config on exit" is unchecked.  Now, I didn't notice this and spent 3 days populating Asbru with all my connections.  This morning I came back and the whole lot has disappeared. Apparently I didn't click the "Save" button in the lower middle of the screen (yeah, my fault).

Just saying that it might be nice to have a safety net for numpties like myself. Auto config saves never hurt anyone, especially if there's a simple versioning/backup system in place.

**Comment by gfrenoy** [comment]
Good point.

Not sure why it is not set by default.  I'd say that likely many users do not have a version/backup system in place (btw this is bad ;-p) and prefer to control when they want to override their options ?  On the other side, today, most of the software have this "auto-save" paradigm (I'm thinking about GDocs first) so people get used to it.

What are the others' thoughts about this ?

If most of you agree is should be set by default, I can do it ; fairly easy to change :)

**Comment by gfrenoy** [comment]
Since nobody told us it was a bad idea ; I changed the default...

**Comment by gfrenoy** [comment]
As said above, "auto save" is more in line with today users' expectations.

But why do you say you need to mess up your config ?  Simply uncheck the option "Automatically save every configuration change" and you're all set.

If you are not confident with this, simply backup the configuration directory (```.config/pac```) before experimenting any change.

If you want to control this better, your may also want to change the parameter ```auto save``` to 0 in your configuration file ```pac.yml``` manually (and restart Ásbrú).

**Comment by jserras** [comment]
When I say mess up the config, is just that, some acidental click on an option, of which there are many, and your gone, no way to know what changed, that is the reason for the save buttons, and also prompts on exit if there are changes so don't see the need for the change, and just like any unix stuff, linux servers, routers, etc.. save your config and changes, actually inline with linux/unix users expectations.
Otherwise the interface can be redesign, no longer makes sense to occupy screen space with a useless save button, but it's the wrong way to go imo.
Hope I don't seam to strong, went with asbru because seems more active and better spirited than pac, but ...
Auto save actually has caused much pain in the past, if its simple software it's fine, but this isn't simple software.
You learn, sometimes from mistakes, to save your work as you go along, not after 3 days, and with a giant save button, can't miss it.

**Comment by gfrenoy** [comment]
João, your points are certainly valid.  A shame we did not have this discussion when I first asked for feedbacks, this is very interesting :-p

Anyway, it's only the default ... If you are not comfortable with this setting, just disable it and the discussion is closed, isn't it ?

About the default, I really think we should move Ásbrú forward and today users' expectations are:
 - I don't want to bother clicking on "save" (please read the initial request again to understand...)
 - I something is wrong, I just go back in the history of my configuration files and revert to a version that was working (does not exist today, maybe we should work on this first)

So what I would suggest at this point is to work on new features like #34 or #95 ; those will bring a better software...
