### ISSUE TITLE
Loki branch - Keepass integration improvement 

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#474]
Hi Team ...

I'm now testing the Asbru Keepass integration and so far so good.

Once I press the Keepass button in one of the connection definitions, I get an empty entry field where I have to type the hostname and then an automated lookup occurs against the Keepass database
![image](https://user-images.githubusercontent.com/37672088/76681797-bdd9a280-65ee-11ea-9506-40063a1bffee.png)

Not a big deal ... but is that possible to automatically fill up the entry field with the 1st word of the node name (not sure for other's but for me the node name 1st word is usually the hostname, and that's what I use to lookup in the Keepass database) ?
![image](https://user-images.githubusercontent.com/37672088/76681823-e6fa3300-65ee-11ea-887e-2610c3d7cae2.png)

Thanks for your support.

**Comment by hanspr** [comment]
The only way to implement this, is if we begin adding "behaviour" options to the keepass integration tab.

But I would not  implement it as a fixed solution. Any users that follow a different strategy  would be permanently searching and deleting an entry that has no use for them. For example I organize asbru and keepass entries by Clients (group). So to me it would be more useful to fill the search box with the group name, because groups names are related in both databases.

So, one possibility would be to add an option to:

+ Fill search entry with : node name, host name, group name (others that would be useful?)

Or don't do any change as this is not a usability issue.

**Comment by gfrenoy** [comment]
Adding more options looks a bit overkill to me ... Keepass configuration happens only once per entry and indeed there are so many different use cases.

That being said, having this big empty window can be confusing, we might want to find something to let he user understand he/she has to type something...

**Comment by hanspr** [comment]
I don't think that is a confusion issue request, is a convenience issue request.

You may add a tooltip or message if you thinks it will help other people. But is already documented on the manual.

As for this request I think he is asking for a convenience to pre fill a fixed value to type less.

**Comment by hanspr** [comment]
> As for this request I think he is asking for a convenience to pre fill a fixed value to type less.

And having a list of preselected entries available to choose from.

**Comment by popxunga** [comment]
> I don't think that is a confusion issue request, is a convenience issue request.
> 
> You may add a tooltip or message if you thinks it will help other people. But is already documented on the manual.
> 
> As for this request I think he is asking for a convenience to pre fill a fixed value to type less.

Exactly ... but I can leave with.
In my case I do have near 300 hosts.
So I need to type every single one to integrate with Keepass. 
Not a big deal as I'll need to do it only once :-)
The node name or the value in the "Tab / Window Title" field would help.
Thanks
Thanks.

**Comment by hanspr** [comment]
@popxunga 

I think this will be a __"will not do"__. Sorry.

As discussed previously as much as the idea could be attractive when having to do a large initial setup, has the inconvenience that it there are many alternative logics for different users.

If you have a better justification to convince us that we must do it, please let us know, otherwise you should close it to clean the board.

**Comment by popxunga** [comment]
Better logic ? No problem. Thanks.
