### ISSUE TITLE
"Retab" button in PCC causes asbru-cm to crash

### ISSUE THREAD

**Issue by nomike** [asbru-cm/asbru-cm#52]
Steps to reproduce:
1. Open 2 terminals and add them to a cluster
2. Open PCC
3. Click the "Explode" button -> the tabs are now detached from the main window into separate windows
4. Click on "ReTab" -> asbru-cm crashes with a segmentation fault

System info:
OS: Ubuntu 17.10 amd64
asbru-cm version: 5.0.0-1
perl version: perl 5, version 26, subversion 0 (v5.26.0) built for x86_64-linux-gnu-thread-multi

**Comment by poffice** [comment]
The same behaviour is observed on **Ubuntu 16.04.3 LTS** with **Perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi**

**Comment by gfrenoy** [comment]
Confirmed as well.  I tried to find the root reason but did not find anything so far.  The "ReTab" operation happens at line [2096 of PACTerminal.pm](https://github.com/asbru-cm/asbru-cm/blob/master/lib/PACTerminal.pm#L2096) called at line [840 of PACPCC.pm](https://github.com/asbru-cm/asbru-cm/blob/master/lib/PACPCC.pm#L840).  Not sure what could be wrong there...

**Comment by gfrenoy** [comment]
> How can I disable the ability to open a separate window ?

As far as I know, this is not an option today.  But if you simply don't select this entry in the menu, it should not be an issue, shouldn't it ?

**Comment by KozlovAO** [comment]
Yes, that's right. But sometimes, by chance, the window is unhooked (touches a mouse) and it is necessary to leave it open that all has not closed...

**Comment by hanspr** [comment]
Hi @nomike 

Me again, I relate to this issue because I use Clusters very often my self. The last changes on the gtk3 branch, have also addressed some of this issues. Among the changes I'm aware:

* If you use windows (not tabs) it is not necessary any more to tab and explode to align them
* Have not seen more crashes related to that action

So hope you could test this issue too in the gtk3 branch to have fresh information to work on if a bug it is still there.

Thanks for your help.
