### ISSUE TITLE
Open all connection of one folder

### ISSUE THREAD

**Issue by mvrk69** [asbru-cm/asbru-cm#534]
Hi,

Would be nice to have an option to right click on one folder on the connection list that would open all connections of that folder.

**Comment by popxunga** [comment]
Hi ...
If you select the group of connections and press the Connet button, it opens all the connections defined in that group. Is this what you're asking for ?

**Comment by mvrk69** [comment]
Yes, if i click the connect button does that.

But what i'm asking for is for having the same functionality when you right click on the group, on that submenu that appears when you right click on a group.

**Comment by popxunga** [comment]
Ok then ... it's just add another option to the context menu what you're asking for. 
That would be easy to implement I guess, as the functionality is already in place.

**Comment by mimmus** [comment]
First day of serious test, I'm adding +1 to most important features missing in my opinion

**Comment by gfrenoy** [comment]
It is already possible to select a group and then click on the "Connect" button to start all connections of the selected group.

I just added a menu entry so that the same feature is available from a right-click on the node.

You can test this on the loki branch or wait for for the 6.3.0 release (no date yet...).
