### ISSUE TITLE
Keepass integration - Username not shown during lookup

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#551]
Hi ...
When setting up a connection to read the credentials from the Keepass database, during the lookup only /Group/Title is shown. 
When there's multiple entries for the same Title with different userid's in the Keepass database, it is impossible to know which one we are selecting because the Keepassx Username value is not shown. Can we get the lookup process changed in order to include the Keepass Username value as well (e.g. /Group/Title/Username ) ?
Thanks.

**Comment by hanspr** [comment]
That is al the information that keepass can give me while listing, to get a username it would require a second pass to unlock for each entry.

And during the execution is requiered that all paths /group/../titles "are unique"

You have to make sure each title is unique inside the same /path

Create more subgroups to separate them

For example

```
/Clients/Company A/Production/server a
/Clients/Company A/Production/server b
/Clients/Company A/Production/server c
/Clients/Company A/Marketing/server a
/Clients/Company A/Marketing/server b
```

But this is bad, because at the time to pull the passord there wont be a way to know which one is the right one.

```
/Company A/Servers/server a
/Company A/Servers/server b
/Company A/Servers/server c
/Company A/Servers/server a
/Company A/Servers/server b
```

You need to organize them so that all paths are unique.

Sorry, can not be done.

If you are not convinced, read the documentation about `keepassxc-cli` and test how it works.

**Comment by hanspr** [comment]
Or rename the titles from a generic name to the hostname, or something to make them unique.

like

```
/Company A/production server
/Company A/testing server
/Company A/www.comany.com
/Company A/erp
/Company A/erp testing
```

**Comment by popxunga** [comment]
Hi @hanspr 
Thanks for the detailed explanation.
If the keepassxc-cli locate verb returns only what I see in the console, then clearly is not possible.
Are you aware of any request on keepassxc github asking to include the userid field in the output produced by the keepassxc-cli locate ? I did a quick search and found nothing. 
Anyway, this is not an Asbru issue but a keepassxc-cli lack of functionality (from my point of view of course).
Thanks.

**Comment by hanspr** [comment]
Even if you request that, and they added, the must important thing again is __not to list__, but to __find the correct key later__ (when the connection needs to pull the username and password).

Even if you have the username, it will get you in trouble later.

I need to find "unique" keys inside the database. Not duplicated ones, because that would cause a popup to request the user to choose the correct one from all the repeated ones you want to use.

And I do not want that, is too slow and messy. It was one of the drawbacks of the previous implementation.

So to get one, and only one correct key at the moment of the connection, I need to make sure there is only one key in existence with that path, the difference can not be a username, it has to be the full path.

At the beginning I want to use the UUID to use as my path to find a key, but they (keepassxc team) removed this option to search. So I had to go for the path. I made a feature request to bring it back, but It has not been solved, and even if the do, by the time they release it and with so many versions of keepassxc-cli that can or no do something it will get complicated.

The best option is to organize all paths to be unique. I think the exercise not only will help the integration, but it will help the organization of keys inside keepass as well.

I'm publishing another amend to the documentation, you may read my thoughts about it there.

https://github.com/asbru-cm/asbru-cm/pull/552/files

**Comment by hanspr** [comment]
To complete the explanation, at the time to connect, I need to call the __show__ command: `keepassxc-cli show database.kpdb 'entry'`

The value __entry__ : if given a small string, will get the __first entry__ with the same title, will ignore any additional ones.

![imagen](https://user-images.githubusercontent.com/1572396/78292117-caf9fb00-74e3-11ea-9b3e-6c6dbfdb5909.png)

The perfect solution would have been if I could search by UUID. This would have allowed to:

* Have repeated titles
* Do not break relations if the nodes are renamed or moved to another group.

But as I said, that possibility is off the table. Is not in my hands.

**Comment by popxunga** [comment]
Hi @hanspr 
Thanks for the complementary explanation.
I briefly tried with locate and show verbs of keepassx-cli and I agree that's not possible.
Once they removed UUID from keepassxc-cli, at least they should have added the UserID field to the output, because in most cases the pseudo-key formed by /Group/Title/Username would work.
But of course that even with a pseudo-key formed by /Group/Title/Username someone can easily create a duplicate.

**Comment by popxunga** [comment]
Closing.
