### ISSUE TITLE
Connection panel resizes on terminal selection open

### ISSUE THREAD

**Issue by hanspr** [asbru-cm/asbru-cm#581]
@syco

Documenting case based on #568 

Connection panel will resize when is displayed on the right and you select some connections.

![79915792-8648ec00-841f-11ea-8eee-a63135966231](https://user-images.githubusercontent.com/1572396/79923629-8afba900-83fb-11ea-91a4-71cfde7a354e.gif)

Apparently is produced by the expansion or contraction of the statistics information, when the length of the "Reset" button changes (longer shorter connection names) or the connected time expands, contracts, creates a connection list resize. It also happens when a terminal is open because the panel tries to recover the space.

![image](https://user-images.githubusercontent.com/1572396/79923268-c053c700-83fa-11ea-83dd-750c20c79432.png)

Disabling the show statistics on the Global Preferences, apparently removes the undesired effect. Have not been able to reproduce under other scenarios but the statistics enabled.

Needs further analysis to detect other possible causes.

**Comment by syco** [comment]
Thanks for opening this and looking at it so quickly.
Enabling statistics for individual connections definitely makes it worse as the button changes size on every selection.

The other reason could be the statistics panel in the info tab, since that's always visible, even with that global option is disabled.
