### ISSUE TITLE
Remove quit button

### ISSUE THREAD

**Issue by ferent** [asbru-cm/asbru-cm#608]
Hello, 

This is open to discussion, but is it actually needed to have a Quit button on the bottom right? Is something I've always wondered why is there, if since Windows 95 all the people hit the top X button to close different windows. 
I know that I can hide the whole button bar, but is just this Quit button the one I don't really see is important. 
Thanks

**Comment by hanspr** [comment]
If you activate the option : Hide on close (which will minimize to tray the window when you click on the "close" window button). You need another way to tell that you actually want to quit (and not close)

The point is that Ásbrú has so many options, that allows many people to work differently. And by working differently, some elements are not relevant for one type of users but are for others.

I use the "Compact" mode, under that working logic, that button is needed.

Eventually we could do some work to hide or show elements depending on the collection of options that are active. In a way that is what I did with the compact mode, but I have never there to touch the traditional mode because many people are already used to it since old good PAC.

**Comment by ferent** [comment]
Is fine then, doesn't hurt, I like UI as clean as possible, that is why I wanted to suggest to get rid of this. But is other people find it is useful and makes sense, proceed to close the ticket. 

Thank you very much for your explanation.

**Comment by hanspr** [comment]
>I like UI as clean as possible

I do as well, clean and as minimalistic as possible. That is why I designed the compact mode.

https://docs.asbru-cm.net/Manual/Preferences/MainOptions/#main-window-layout

The connection manager is detached from the working terminals (tabbed or individual) and hide show the connection manager from the tray; as a kind of popup menu.

![imagen](https://user-images.githubusercontent.com/1572396/81418288-13738c80-9112-11ea-9932-6130370a295a.png)

**Comment by gfrenoy** [comment]
Changing the location of the quit button would indeed something that must be considered when reviewing the overall UX of the application... But as it is today, as already explained by Hans, it is useful.
