### ISSUE TITLE
Copy from tmux buffer to system buffer (clipboard)

### ISSUE THREAD

**Issue by wcasanova** [asbru-cm/asbru-cm#631]
hi, i have a problem copying from Ásbrú with tmux, to my system clipboard .. it only happens with Ásbrú, because for example with Konsole if you copy to the system clipboard ..

I leave some tmux settings.

https://github.com/gpakosz/.tmux

**Desktop (please complete the following information):**
 - OS: Archlinux / Plasma
 - Version : loki  2fe4c2f

**Comment by gfrenoy** [comment]
Sorry I don't understand what does not work for you.  Can you describe the steps to reproduce it ?

**Comment by wcasanova** [comment]
thanks, it was another problem, in case it was copying from a remote tmux session, to my local clipboard, for the moment it works by selecting the text with the mouse and without pressing the backspace key

**Comment by davidgut1982** [comment]
After sitting with this for a while I've put together a working implementation — PR #1187 addresses this directly.

**The approach:** Rather than patching VTE (which upstream has explicitly rejected since GNOME bug #795774 in 2018), the implementation installs a passive `Expect::log_file` observer in `asbru_conn` that watches raw terminal output for OSC 52 escape sequences. When one is found, it's forwarded to `PACTerminal` via the existing `ctrl()` Unix-socket channel, which then writes to the GTK3 clipboard. VTE is never touched.

**Verified working on Manjaro Linux / VTE 0.82 / tmux 3.6a:**
- Direct `printf ']52;c;<base64>\'` in PACShell and SSH sessions ✅
- tmux mouse-select → system clipboard (the main use case from this issue) ✅
- Full UTF-8 / Unicode content (box-drawing characters, emoji, accented letters) ✅
- Kill-switch: `ASBRU_OSC52_DISABLE=1` env var disables it entirely ✅

**Security:** The feature is **opt-in** (disabled by default). Users enable it in Preferences → General → *Allow OSC 52 clipboard writes*. The implementation also validates base64 strictly, enforces a 100 KB size cap per sequence, and never honours the `?` query form (which would read the clipboard back to the remote — an exfiltration vector).

Two spec-compliance edge cases are worth noting for anyone reviewing:
1. tmux sends an *empty* targets field (`]52;;<base64>`) by default. Per the xterm `ctlseqs` spec this means "use default" (CLIPBOARD) — the scanner normalises this rather than dropping it.
2. Perl's `MIME::Base64::decode_base64()` returns bytes without the UTF8 flag set. Passing those bytes directly to `Gtk3::Clipboard::set_text()` causes the GLib binding to treat them as Latin-1, producing mojibake for non-ASCII text. Fixed with `Encode::decode('UTF-8', ...)` before the clipboard write.

Happy to address any feedback on the PR.
