### ISSUE TITLE
VNC connection + jump host picks wrong port

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#661]
Hi, as in topic when I try to connect with VNC (port 5900) using jump host of the same destination (port 5900 cut out on infrastructure) asbru tries to establish connection on 5901 instead of 5900 (set in connection).
When I set it to 5899 it tries to establish connection with 5899.
So in simple words no matter if I set port to 5900 or 5901. It connects to 5901 in both cases.

asbru v6.3 loki
 
```
Fri Jul  3 14:37:31 2020
 DecodeManager: Detected 4 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConn:       connected to host 127.0.0.1 port **5901**
channel 3: open failed: connect failed: Connection refused
 CConn:       End of stream
Exit request sent.

DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Fri Jul  3 14:37:31 2020)

TigerVNC Viewer 64-bit v1.9.0
Built on: 2020-01-23 18:03
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.

Fri Jul  3 14:38:20 2020
 DecodeManager: Detected 4 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConn:       connected to host 127.0.0.1 port **5899**

```

**Comment by gfrenoy** [comment]
Port 5901 is used on your local machine to be the entry point of the tunnel.  We have to take an arbitrary port for that, by default, we take the target port + 1 and check if the port is free:

https://github.com/asbru-cm/asbru-cm/blob/a3fb65fab9c0a86f347002827ae21d89e2ef9a12/lib/asbru_conn#L888-L902

This is by designed but should not be an issue.

So your real issue is what the message `channel 3: open failed: connect failed: Connection refused` suggests : the tunnel has not been created correctly !

Don't you see any error suggesting the jump host could not be reached ?  Or maybe the connection has been established and immediately dropped, for some reasons ?

As a matter of fact, you should see a connection to your jump server in your process list ; do you see it ?

**Comment by vibo69** [comment]
so explain to me what happens when I set port to 5899 and I get this: 

Fri Jul  3 14:38:20 2020
 DecodeManager: Detected 4 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConn:       connected to host 127.0.0.1 port **5899**
channel 3: open failed: connect failed: Connection refused

is this a port binded on my local machine or remote one? because my 5900 is taken

**Comment by gfrenoy** [comment]
> what happens when I set port to 5899

Same as explained above ; the tunnel is not established.

And if you read the code of `_getLocalPort` ; you can see I made a mistake in my description : we don't do "+1" ; we try first to use the same port on the local machine.  So yes, 5900 is definitely taken on your machine.

> is this a port binded on my local machine or remote one?

It *should* be bound on your local machine but it did not work ; the tunnel failed to be created.

**Comment by vibo69** [comment]
so as I understand problem exists in my case when jump host is the same host as destination one with existing bind to 5900 when I want to connect to 5900 (x11vnc). I am not a programmer.. did not read the code carefully. 
so what I expect is to connect to VNC in that exact case. can U correct this? ;)

**Comment by gfrenoy** [comment]
No this is not the root cause.  It should work with any port on your machine, it does not matter at all.  `_getLocalPort` picks one that is close to the target one but it could have been a "random" pick, it would be the same.

The root cause is that your tunnel is not properly established with the jump host.  Or at least does not remain connected.

Try to understand why the jump host cannot remain connected and it should work fine.  Try to answer the questions above, it will hopefully bring more information to troubleshoot this further.

**Comment by vibo69** [comment]
I didn't have time to respond lately to this but today I have this issue again. because traffic is filtered on the infrastructure.. the only way I can connect is ssh but need to connect to vnc on destination host. so I use jump host of the same destination host.
port 5900 is binded on my machine (for my own vnc server). 5901 is also binded. so asbru picks 5902. as I understand this is first free port to bind (on source host). then it tries to connect to this port and connection is refused. why? i double checked this also trying to bind 5900-5902 on destination machine. still connection is refused. something is wrong here.. it should pick whatever port on source host and connect to exactly specified destination port in connection configuration 

TigerVNC Viewer 64-bit v1.9.0
Built on: 2020-06-16 19:36
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.

Mon Oct 26 09:43:36 2020
 DecodeManager: Detected 4 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConn:       connected to host 127.0.0.1 port 5902
channel 3: open failed: connect failed: Connection refused

Mon Oct 26 09:43:37 2020
 CConn:       End of stream
Exit request sent.

**Comment by gfrenoy** [comment]
> it should pick whatever port on source host

You should not focus on the local port, it should indeed pick any free port.
As said above:

*The root cause is that your tunnel is not properly established with the jump host. Or at least does not remain connected.*

Again, please answer the questions already asked above, it will hopefully help:

- Don't you see any error suggesting the jump host could not be reached ?
- Or maybe the connection has been established and immediately dropped, for some reasons ?
- Do you see a connection to your jump server in your process list ?
