### ISSUE TITLE
Close app on last terminal close : cannot find the option

### ISSUE THREAD

**Issue by necarnot** [asbru-cm/asbru-cm#696]
**Describe the bug**
I cannot find the option allowing the complete shutdown of the app when the last terminal is closed.

**To Reproduce**
1. On one of my computers, this useful behavior is working
2. I don't know how I managed to get it
3. On all my other computers, I can't find it, this is sad

**Expected behavior**
I hope I'm just blind and some good soul will guide me.

**Environment (please complete the following information):**
 - OS: XUbuntu 20.04
 - Ásbrú Version 6.2.1

**Comment by hanspr** [comment]
I do not see that has ever been an option (not that I remember). Is not even documented on the manuals.

https://docs.asbru-cm.net/Manual/Preferences/MainOptions/

If you are using the Traditional mode,

I would recommend using options like : 
* Hide to tray instead of closing. So you can hide the interface when is not in use.

Or you may test the Compact mode (check the manuals).

But in any of those cases the Application would not quit. It would simply hide to a system tray.

If you think is an important feature to add, please explain the user case where would it be relevant.

I personally do not think it would be convenient, Ásbrú is not a terminal. Is a full Connection Manager.
* Its start up times are large compared to starting a single terminal.
* Currently I do not see it consuming considerable resources to affect a small PC. I run it in a very small notebook with an Atom processor and it has never bother me to have it loaded and hidden.

**Comment by gfrenoy** [comment]
> I do not see that has ever been an option (not that I remember)

Me neither... It must be something else.

**Comment by necarnot** [comment]
Hello, and thank you for your answer.

First, I agree with Hans about the fact that Asbru is a full CM. I run it all day long, all year long. It's the first thing I start in the morning, and the last one to shut at night.
Though, it can happen I'm using my computer to watch a movie or do video editing or other things, so I'm sometimes shutting down ACM.
I've just double-checked the settings on the computer where I thought it was shut, and here's the catch : 
The checkbox about hiding in the traybar is checked, but no icon appears when ACM is trying to hide there.
I'm using a pristine XUbuntu 20.04 with the pristine and default XFCE wm.
I guess the next advice you'll give to me will be to open another issue about this "way-too-hided hided traybar icon"?

**Comment by hanspr** [comment]
Well about creating a new issue, this thread's title is surely different from where we are going now.

And the titles and the content are relevant for documentation and when other people looks for a solution to a problem. When you search in a search engine you want that search engine to point you to a valuable thread that solves the problem that you have. And this thread could easily get wrongly indexed for future users searching for an answer to : "System tray icon is not showing in XUbuntu 20.04" 

Now, if your desktop does not show your system tray icon and you have the option "Hide to system tray instead of closing", to Exit, you must click on the "Quit" button, and not the "window close button". In Both "Traditional" or "Compact mode"

![imagen](https://user-images.githubusercontent.com/1572396/95350981-56cf5400-0886-11eb-9eee-0ff1985f72bf.png)

![imagen](https://user-images.githubusercontent.com/1572396/95350991-5afb7180-0886-11eb-8dd4-c20920cda513.png)

My suggestions are

* Check if your desktop environment has a system tray running and and if there are any published changes to it, new compatibility issues or advices about it.
* Check all system icon related options in your settings

![imagen](https://user-images.githubusercontent.com/1572396/95349830-1d4a1900-0885-11eb-819e-e36a408c219c.png)

![imagen](https://user-images.githubusercontent.com/1572396/95349863-233ffa00-0885-11eb-9f5f-ec2c354580a2.png)

If everything looks ok, and still you can not see he system tray icon.

At least change the title to the correct issue we have to investigate and if it is not possible then open a new issue. And add images of your settings and how does your system tray desktop looks like.

I would have to set up a virtual machine to be able to replicate the issue.

**Comment by hanspr** [comment]
@necarnot 

Just finished installing a virtual machine with xubuntu 20, full updates and out of the box, and everything works fine with the system tray and exit buttons.

__System Tray Icon visible__

![imagen](https://user-images.githubusercontent.com/1572396/95356217-0e1a9980-088c-11eb-89e9-fe428922b7c1.png)

__Interface hidden, icon available and left click menu available__

![imagen](https://user-images.githubusercontent.com/1572396/95356303-238fc380-088c-11eb-88df-974ca2caf6e5.png)

__Settings__

![imagen](https://user-images.githubusercontent.com/1572396/95356343-2c809500-088c-11eb-8c0f-9d4c6bee6f11.png)

![imagen](https://user-images.githubusercontent.com/1572396/95356366-31454900-088c-11eb-8ff1-f118f5a17373.png)

Sorry, I do not see any issues.

**Comment by necarnot** [comment]
Hello,

Just a quick msg to thank Hans for having taken the time to set up a VM and test this point.

Have a nice day.

-- 
Nicolas
