### ISSUE TITLE
add more options for the pre exec feature

### ISSUE THREAD

**Issue by NRGLine4Sec** [asbru-cm/asbru-cm#704]
It would be great if you can add more options for the pre exec feature. For exemple, I run quite often Shuttle before start a connection and I have to run it in an other terminal, because shuttle ask for the password of the destination target and we can't define it in Asbru.
It would be nice to configure shuttle with a password stored in keepassxc, like for the password of the connection.

There is also the same problem when it is necessary to initiate a VPN connection before the SSH connection. Today, I use `nmcli c up <connection_id>` in the pre exec command to do it, but it could be nice to add this like a feature, like for the jump host.

**Comment by gfrenoy** [comment]
> It would be great if you can add more options for the pre exec feature

If you right click on the input field, you'll have access to all kind of variables to dynamically build your pre-connection command:
![image](https://user-images.githubusercontent.com/981546/96303987-a4249180-0ffb-11eb-93fb-0ab16e9a0db6.png)

What other variable that is not yet available would you need ?

**Comment by gfrenoy** [comment]
I've added some words in the documentation about this.  I believe there's already everything in Ásbú to address your use case.  So let me close this issue for now, feel free to re-open or create a new one if something should be missing.

**Comment by NRGLine4Sec** [comment]
Hi @gfrenoy,
I have tried to do a sshuttle tunnel in pre exec command with KeePassXC username/password variable, but without success.
Can you give me a example to do it the best way ?

PS: sshuttle need sudo

**Comment by gfrenoy** [comment]
Can you describe what Ásbrú is missing and/or what does not work as expected ?

**Comment by NRGLine4Sec** [comment]
I have to do a sshuttle tunnel before starting connection (sometimes I have to mount two following tunnels with sshuttle) and I don't succeed to do it, I try to do pre exec command but, the sudo needed seems to freeze asbru, I try to do it in a dedicated connection with generic command method because we can run it with the sudo option, but I don't success to add KeePassXC password/username because the fields are grayed out. So I tryed to put password with "Expect and Execute" option and the KeePassXC password variable, but without success, so I ask you the better way to do it if it currently possible in Asbru, or if you can add this feature otherwise.

**Comment by gfrenoy** [comment]
> the sudo needed seems to freeze asbru

Is it asking for a password ?  Did you try to add the command in /etc/sudoers to avoid this ?

> I don't success to add KeePassXC password/username because the fields are grayed out.

Mmm, I don't see anything in the code that would gray those options out ... Can you maybe add a screenshot, I don't believe I understand this right.

>  so I ask you the better way to do it if it currently possible in Asbru

This looks correct to me but you probably need to create a custom script outside of Ásbrú to avoid the complexity inside Ásbrú.

> or if you can add this feature otherwise.

Which feature ?  Please specify exactly what needs to be changed.  Just having an idea is only the beginning of the work, analyzing how the software is currently working and define in details the required modification is a huge job as such ; if you want to make this progressing, be as detailed as possible.

Btw, this issue is closed as what is requested is already implemented :-/  If you want to chat to have some help, please join our IRC channel...
