### ISSUE TITLE
Can't set authentication parameters

### ISSUE THREAD

**Issue by Frantzd** [asbru-cm/asbru-cm#759]
Hello,

when I create new connections I can't set the authentication parameters anymore : 
user / password is grayed :-(

**Environment :**
 - OS:  Ubuntu 18.04
 - Ásbrú Version 6.2.2

**Comment by gfrenoy** [comment]
This is obviously not the "normal behaviour" of the application.  There must be something specific with your case.

Are you sure the "User / Password" option is correctly set ?

![image](https://user-images.githubusercontent.com/981546/107159154-93bf6a80-698e-11eb-99a3-0b55cc05c821.png)

Does this also happen if you start from a "blank" configuration ?

**Comment by Frantzd** [comment]
Here is a copy of the window with the grayed authentication parameters :

![2021_02_09_10h47](https://user-images.githubusercontent.com/218184/107345870-52c97200-6ac4-11eb-97ab-e3d7b93fc474.png)

What do you mean by "blank" configuration ?

I did not have this problem while setting my first connections.

**Comment by gfrenoy** [comment]
> window with the grayed authentication parameters :

Aah, now I remember, yes ; it's a known issue, see #735 for a workaround.  Let me know if this works for you.

And this should be fixed in the next version.

> What do you mean by "blank" configuration ?

When you start from a fresh configuration file.  You can do this with the following command:

```
asbru-cm --config-dir=/tmp/asbru-test
```

This will create new configuration files in `/tmp/asbru-test` and preserve your working configuration that should be in `~/.config/asbru`.

**Comment by Frantzd** [comment]
Hello,

I've upgraded to the latest version 6.3.1 and the bug disappeared :-)

Thank's !
