### ISSUE TITLE
With vspilt on vim, while trying to jump to other spilt window using CTRL+ww, it asks for terminal window closure.

### ISSUE THREAD

**Issue by PabitraPati** [asbru-cm/asbru-cm#785]
1 - Open a file F1  using vim
2 - OPen another file F2 with vspilt
3 - Now the focus is on F2.
4 - In vim try switching focus to the other split (to F1) using CTRL+ww.

ON Pressing the first w iteself, Asbru Cm will ask for confirmation to close the current terminal.

Also as per documentation, the priority is least for terminal
Also, it doesn't allow to change the key bindings.

While in terminal, that should be highest priority instead of Asbru CM
User should be allow to change their keybindings as well

**Comment by gfrenoy** [comment]
When you do `Ctrl+w` and then `w`, `Ctrl+w` is not processed by vim so Ásbrú is using it and the default behaviour is to close the terminal.

Don't think we can fix this ...

But you can change this by deleting the keybinding in `Preferences` > `Keybindings`, then selecting `Terminal` > `Close Terminal` and hit the `DEL` key on your keyboard:

![image](https://user-images.githubusercontent.com/981546/109229276-5dbe1b00-77c3-11eb-8c82-c6de0c76bad9.png)

**Comment by pandiloko** [comment]
I noticed some more conflicts with other shortcuts as well. For example:

 - in the command line (bash) the readline shortcut for delete word (CTRL-w) shows the dialog to close the tab (same case as this issue). Fixed by deleting the keybinding
 - in vim when using file completion (c-x, c-f) Also fixed by deleting the keybinding from Main Window (there was another one in Connection List)

**Comment by gfrenoy** [comment]
It won't be possible to find default keybindings that has no conflict with any another application...

You can configure your keybindings as you wish, that's the purpose and it works as expected.
