### ISSUE TITLE
Connection no longer working with KeePassXC integration

### ISSUE THREAD

**Issue by TwinkleToes777** [asbru-cm/asbru-cm#821]
**Describe the bug**
It never connects, showing the usage of ssh command, as if it would've been a wrong command usage, here's the log:
```
RECONNECTING WITH TestServer (Sat Jun 26 10:30:29 2021) attempt:10

GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/share/perl5/Gtk3.pm line 555.
LOG **: Initializing XApp GtkModule at /usr/share/perl5/Gtk3.pm line 555.
LOG **: Adding a Favorites shortcut to GtkPlacesSideBars at /usr/share/perl5/Gtk3.pm line 555.
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command]

DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Sat Jun 26 10:30:30 2021)
```
**To Reproduce**
1. open edit connection in the connection and press on KeePass icon, enter keepass password and select a existing password entry
2. try to connect
3. observe it failing

**Expected behavior**
to just work

**Screenshots**

**Environment (please complete the following information):**
Linux Mint 20.1
Ásbrú Version 6.3.2

**Additional context**

**Comment by xattack** [comment]
Hi 

   I believe i know whats going on with your issue ...

   When you use Keepass and select an existing account with password , and tried to connect later you get something like this 

![Screenshot from 2021-06-30 16-55-29](https://user-images.githubusercontent.com/8902460/124038950-a121d380-d9c7-11eb-9290-7f952ad11967.png)


   In my case , it was because KeePassXC , not only put username and password, also modified the IP address as you can see
 
![WTF4](https://user-images.githubusercontent.com/8902460/124039076-d3cbcc00-d9c7-11eb-8e7a-0a74e2c80efa.png)

  I didn't notice at all , and whe tried to connect , obviously i couldn't. So may be its you case too. Check it , may be this is the solution

**Comment by TwinkleToes777** [comment]
Thank you so much! That was it, it now works.
