### ISSUE TITLE
Using  zero port on Jump host configuration

### ISSUE THREAD

**Issue by Magic03** [asbru-cm/asbru-cm#888]
**Can't specify 0 as port number in Jump host configuration**
We can specify 0 as a port number on "Connection Details" tab for SSH connection. In this case port will be as dfined in ~/.ssh/config file but same can't be done on a Jump host

**To Reproduce**
1. For SSH connection Go to 'Network Settings' tab
2. Select 'Use a Jump Host'
3. Enter hostname or IP and port = 0

**Expected behavior**
Port saved as enterd and settigns from  ~/.ssh/config  file should be used if port equals 0 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux Mint 20.2
 - Ásbrú Version 6.3.2

**Comment by xattack** [comment]
Hi @Magic03 

I verified your sayings and found it inaccurately in some extension.

 I defined a connection I already know it works using a Jump host to connect. Instead of port 22 used 0 , also 
on the Jump host definition

 
![asbru-Connection-details](https://user-images.githubusercontent.com/8902460/143483446-564555a7-c8cb-4da4-a279-0f781caf9d9f.png)

![asbru-Network-Settings](https://user-images.githubusercontent.com/8902460/143483468-bee5c9d2-570d-4859-acab-36db51f1fd95.png)

for some reason it keeps a number 1 on the port instead of zero after saving the connection.

These connections, both destiny host and jump host , are already defined in .ssh/config file as usual connection 

Host hostname
        Hostname a.b.c.d
        User username
        Port 22
 
I'm able to connect whithout any issue.   Perhaps  Asbru's version ?

OS: Linux Mint 19.3 
Asbrú  Version 6.3.3

**Comment by gfrenoy** [comment]
> for some reason it keeps a number 1 on the port instead of zero after saving the connection.

The value is saved correctly but when reloading the value in the default GtkSpinButton definition, it does not accept 0.

I just pushed a commit for `loki` that changes this ... If someone can double check it works as expected in `loki` ; I can probably add this for 6.3.3 as well.
