### ISSUE TITLE
Guessing the hostname with <ctrl>+<shift>+<g> doesn't work with zsh

### ISSUE THREAD

**Issue by nomike** [asbru-cm/asbru-cm#9]
When I'm using ZSH and press <ctrl>+<shift>+<g> "hostname\n" is sent to the terminal and the hostname command writes it to STDOUT, but it's not picked up by asbru-cm.

On another machine I'm using antigen with oh-my-zsh with the following config:
```
# load antigen
source /usr/share/zsh-antigen/antigen.zsh

# use oh-my-zsh
antigen use oh-my-zsh

# load some modules
antigen bundle git
antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle dircycle
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

# load theme
antigen theme nomike/agnosterzak-ohmyzsh-theme agnosterzak

# finish antigen initialization
antigen apply
```

And when I press the shortcut there,  "hostname" is run, and at the new prompt "##__PAC__PIPE__##" is printed. The status bar is showing "- Status: PIPE_WAIT[60][##__PAC__PIPE_##]" and asbru-cm is stuck for 60 seconds until it runs into a timeout. The hostname is also not picked up.

Ugly workaround: switch to bash, press the key-combination, <ctrl>-<d> back to zsh.

**Comment by gfrenoy** [comment]
I was able to reproduce the same behaviour as described in the second part of your description.  In my case, the shell is [fish](https://fishshell.com/).  On another machine that has zsh, there is no problem with CTRL+SHIFT+G.

So at this stage, I'm not sure the shell is really the root cause.  Maybe some control characters or colors that are not recognized...

**Comment by hanspr** [comment]
Hi @nomike 

I tested the instruction `Ctrl+Shift+G` and I do not see the issue on the gtk3 branch.

![imagen](https://user-images.githubusercontent.com/1572396/69906182-232dbe80-1385-11ea-9943-cfd8ed6e1654.png)

Hope you could test the gtk3 branch and tell us if this bug is still there or maybe with all the changes we have made has been removed. Or have fresh information to work with.

To test the gkt3 branch, install asbru from the instruction pages at : [https://github.com/asbru-cm/asbru-cm/tree/gtk3](https://github.com/asbru-cm/asbru-cm/tree/gtk3)

Or clone the branch and install dependencies, what you consider easier.

Thanks, for your help.
