### ISSUE TITLE
Cannot restore from connections YAML file on Ubuntu 22.4

### ISSUE THREAD

**Issue by telemix** [asbru-cm/asbru-cm#959]
When I try to "import connections" from a previously saved YAML file, it imports a maximum of 1 connection but the yellow "importing.." alert box never goes away an no more of the 30 odd connections I have in that file import. If I shut it down, the single "imported" connection disappears.

I have never had an issue importing before, but this is the first time I have run Ubuntu 22.4.

I am running asbru-crm 6.3.3

Obviously a bit of a killer!

edit -

works fine on 6.3.4 installed via snap.

**Comment by danielraab** [comment]
Same here.

I think the problem is the same as here: https://github.com/asbru-cm/asbru-cm/issues/816

This error message appears when starting via console:
*** unhandled exception in callback:
***   Salt must be exactly 8 bytes long at /opt/asbru-cm-loki/lib/PACUtils.pm line 2713.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.

Error occurs on simple save operations too. 
Have not tried to exchange the perl-crypt-cbc (libcrypt-cbc-perl).

**Comment by pavigor** [comment]
Same here with Ubuntu 22.04

**Comment by toushin-taishi** [comment]
Same with Pop OS 22.04. 
The fix is applied in the Loki branch as of this writing.
https://docs.asbru-cm.net/General/Installation/
