### ISSUE TITLE
AppImage not starting on Kubuntu 22.04

### ISSUE THREAD

**Issue by cebas** [asbru-cm/asbru-cm#998]
**Describe the bug**

Running the AppImage from a terminal, some errors are shown and the program doesn't start:

```
$ ./asbru-cm-6.4.0-1-x86_64.AppImage
(process:191744): GLib-CRITICAL **: 00:56:55.477: g_file_test: assertion 'filename != NULL' failed
Gtk-Message: 00:57:00.424: Failed to load module "xapp-gtk3-module"
Gtk-Message: 00:57:00.657: Failed to load module "colorreload-gtk-module"
Gtk-Message: 00:57:00.657: Failed to load module "window-decorations-gtk-module"
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 191771
INFO: Language detected : en_US.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : other
INFO: Config directory is '/home/cebas/.config/asbru'
WARN: No configuration file found in '/home/cebas/.config/asbru', creating a new one...
INFO: Virtual terminal emulator (VTE) version is 0.62
INFO: Theme directory is '/tmp/.mount_asbru-dNoKTF/opt/asbru-cm/res/themes/default'
INFO: Trying to loading Unity specific tray icon package...
WARNING **: Failed to load shared library 'libappindicator3.so.1' referenced by the typelib: Error loading shared library libappindicator3.so.1: No such file or directory at /tmp/.mount_asbru-dNoKTF/usr/local/lib/perl5/site_perl/Glib/Object/Introspection.pm line 110.
INFO: Using Unity tray icon
WARN: Adding new keybinding [Ctrl+F4] for [Tabs]/[Close current Tab]...
(several more similar warnings)
Could not locate symbol app_indicator_new at /tmp/.mount_asbru-dNoKTF/opt/asbru-cm/lib/PACTrayUnity.pm line 151.

```
libappindicator3-1 is not installed on this Linux.

on another Kubuntu 22.04 that is a lot more clean (almost a fresh install), also not having libappindicator3-1 installed, it works, but shows these messages:

```
$ ./asbru-cm-6.4.0-1-x86_64.AppImage
Gtk-Message: 00:55:30.060: Failed to load module "colorreload-gtk-module"
Gtk-Message: 00:55:30.063: Failed to load module "window-decorations-gtk-module"
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 2692
INFO: Language detected : en_US.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : other
INFO: Config directory is '/home/cebas/.config/asbru'
WARN: No configuration file found in '/home/cebas/.config/asbru', creating a new one...
INFO: Virtual terminal emulator (VTE) version is 0.62
INFO: Theme directory is '/tmp/.mount_asbru-ikOMCp/opt/asbru-cm/res/themes/default'
INFO: Trying to loading Unity specific tray icon package...
WARNING: AppIndicator is missing --> there might be no icon showing up in the status bar when running Unity!
INFO: Using Gnome tray icon
WARN: Adding new keybinding [Alt+n] for [Main Window]/[Show/Hide connections list]...
(several more similar warnings)
```

**To Reproduce**
Run the AppImage from a terminal on Kubuntu 22.04

**Expected behavior**
Asbru starts and shows the main window.

**Environment (please complete the following information):**
 - OS: Kubuntu 22.04
 - Ásbrú Version 6.4.0 in AppImage

**Comment by gfrenoy** [comment]
Thanks for the report.  I did try with a fresh KUbuntu 22.04.1 LTS live image and it's working fine for me.  It does not crash trying to load AppIndicator3, even if it's not installed ... Strange.  In your case, it looks like it's not fully installed or deinstalled so it's trying to load it but fails.  I cannot find how to reproduce this.

But, according to #997, it should actually not even try to load it.  We should only use AppIndicator if you are running Unity.

I'll publish 6.4.1 that will include a fix that will hopefully this issue as well.

Stay tuned.

**Comment by mcarans** [comment]
It won't start for me on Kubuntu 22.10 with similar error.

**Comment by jinformatique** [comment]
Hello, I'm on KDE Neon 22.04 and the configuration file is not supported. I tried both curl and appimage.
This is the error with curl:

```
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | distro=neon version=22.04 codename=jammy arch=x86_64 sudo -E bash
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact asbru-cm for further assistance.
 !!!!: 
 !!!!: URL: https://github.com/asbru-cm/asbru-cm
 !!!!: 
 !!!!: Last 20 log lines from .csm_setup_bxZPzHxhV (might not be errors, nor even relevant):
 !!!!:
 !!!!: > ii  gnupg                                             2.2.27-3ubuntu2.1
 !!!!: > all          GNU privacy guard - a free PGP replacement
 !!!!: > ii  gnupg-l10n                                        2.2.27-3ubuntu2.1
 !!!!: > all          GNU privacy guard - localization files
 !!!!: > ii  gnupg-utils                                       2.2.27-3ubuntu2.1
 !!!!: > amd64        GNU privacy guard - utility programs
```

This is the error with appimage:
```
$ ./asbru-cm-6.4.0-1-x86_64.AppImage
Gtk-Message: 11:04:51.137: Failed to load module "colorreload-gtk-module"
Gtk-Message: 11:04:51.138: Failed to load module "window-decorations-gtk-module"
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 115203
INFO: Language detected : en_GB.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : other
INFO: Config directory is '/home/jean/.config/asbru'
WARN: No configuration file found in '/home/jean/.config/asbru', creating a new one...
INFO: Virtual terminal emulator (VTE) version is 0.62
INFO: Theme directory is '/tmp/.mount_asbru-WdGm78/opt/asbru-cm/res/themes/default'
INFO: Trying to loading Unity specific tray icon package...
WARNING **: Failed to load shared library 'libappindicator3.so.1' referenced by the typelib: Error loading shared library libappindicator3.so.1: No such file or directory at /tmp/.mount_asbru-WdGm78/usr/local/lib/perl5/site_perl/Glib/Object/Introspection.pm line 110.
INFO: Using Unity tray icon
WARN: Adding new keybinding [Alt+F] for [Favourites Tree]/[Remove connection from favourites]...
WARN: Adding new keybinding [AltCtrl+x] for [Terminal]/[Reset Terminal]...
WARN: Adding new keybinding [Ctrl+C] for [Terminal]/[Copy selection to clipboard]...
WARN: Adding new keybinding [Ctrl+Page_Down] for [Tabs]/[Next Tab]...
WARN: Adding new keybinding [Ctrl+T] for [Main Window]/[Open a local shell]...
WARN: Adding new keybinding [Ctrl+c] for [Connections Tree]/[Copy node]...
WARN: Adding new keybinding [Ctrl+ampersand] for [Terminal]/[Send Cisco interrupt keypress]...
WARN: Adding new keybinding [Ctrl+g] for [Terminal]/[Guess hostname]...
WARN: Adding new keybinding [Alt+n] for [Main Window]/[Show/Hide connections list]...
WARN: Adding new keybinding [AltCtrl+s] for [Terminal]/[Open SFTP session]...
WARN: Adding new keybinding [Ctrl+Page_Up] for [Tabs]/[Previous Tab]...
WARN: Adding new keybinding [AltCtrl+X] for [Terminal]/[Reset Terminal and Clear window]...
WARN: Adding new keybinding [Ctrl+w] for [Terminal]/[Close Terminal]...
WARN: Adding new keybinding [Ctrl+D] for [Terminal]/[Duplicate connection]...
WARN: Adding new keybinding [F2] for [Connections Tree]/[Rename node]...
WARN: Adding new keybinding [Ctrl+f] for [Connections Tree]/[Find in connection tree]...
WARN: Adding new keybinding [Ctrl+N] for [Terminal]/[Close disconnected sessions]...
WARN: Adding new keybinding [Ctrl+F3] for [Terminal]/[Find Terminal]...
WARN: Adding new keybinding [Alt+f] for [Connections Tree]/[Add connection to favourites]...
WARN: Adding new keybinding [Alt+r] for [Connections Tree]/[Toggle protection]...
WARN: Adding new keybinding [Ctrl+Tab] for [Tabs]/[Last focused Tab]...
WARN: Adding new keybinding [Ctrl+q] for [Terminal]/[Exit Ásbrú]...
WARN: Adding new keybinding [Ctrl+Return] for [Terminal]/[Start Terminal]...
WARN: Adding new keybinding [Ctrl+q] for [Main Window]/[Exit Ásbrú]...
WARN: Adding new keybinding [Ctrl+v] for [Connections Tree]/[Paste node]...
WARN: Adding new keybinding [Ctrl+F4] for [Tabs]/[Close current Tab]...
WARN: Adding new keybinding [Ctrl+plus] for [Terminal]/[Zoom in text]...
WARN: Adding new keybinding [Alt+e] for [History Tree]/[Edit selected node]...
WARN: Adding new keybinding [Ctrl+W] for [Terminal]/[Disconnect Terminal]...
WARN: Adding new keybinding [Alt+e] for [Terminal]/[Edit Connection]...
WARN: Adding new keybinding [CtrlAlt+r] for [Terminal]/[Remove terminal from cluster]...
WARN: Adding new keybinding [Alt+n] for [Terminal]/[Show/Hide connections list]...
WARN: Adding new keybinding [Ctrl+p] for [Terminal]/[Paste terminal password]...
WARN: Adding new keybinding [undef-infotab] for [Tabs]/[Got to Info Tab]...
WARN: Adding new keybinding [Shift+Insert] for [Terminal]/[Paste selection into terminal]...
WARN: Adding new keybinding [Ctrl+f] for [Main Window]/[Find in connection tree]...
WARN: Adding new keybinding [Ctrl+t] for [Connections Tree]/[Collaps tree completly]...
WARN: Adding new keybinding [Ctrl+b] for [Terminal]/[Paste and regex delete]...
WARN: Adding new keybinding [Ctrl+x] for [Connections Tree]/[Cut node]...
WARN: Adding new keybinding [Ctrl+0] for [Terminal]/[Zoom reset text]...
WARN: Adding new keybinding [Alt+e] for [Favourites Tree]/[Edit selected node]...
WARN: Adding new keybinding [Ctrl+f] for [Terminal]/[Find in connection tree]...
WARN: Adding new keybinding [CtrlShift+F4] for [Terminal]/[Close all tabs]...
WARN: Adding new keybinding [Alt+c] for [Connections Tree]/[Connect selected node]...
WARN: Adding new keybinding [Alt+e] for [Clusters Tree]/[Edit selected node]...
WARN: Adding new keybinding [Ctrl+minus] for [Terminal]/[Zoom out text]...
WARN: Adding new keybinding [Alt+e] for [Connections Tree]/[Edit selected node]...
WARN: Adding new keybinding [Ctrl+R] for [Terminal]/[Restart connection (close and start)]...
WARN: Adding new keybinding [Alt+F] for [Connections Tree]/[Remove connection from favourites]...
WARN: Adding new keybinding [Ctrl+d] for [Connections Tree]/[Clone connection]...
WARN: Adding new keybinding [Ctrl+I] for [Terminal]/[Show the Info tab]...
WARN: Adding new keybinding [Ctrl+V] for [Terminal]/[Paste clipboard into terminal]...
WARN: Adding new keybinding [Ctrl+r] for [Connections Tree]/[Expand tree completly]...
WARN: Adding new keybinding [F11] for [Terminal]/[Go full screen]...
Could not locate symbol app_indicator_new at /tmp/.mount_asbru-WdGm78/opt/asbru-cm/lib/PACTrayUnity.pm line 151.
```

I'll have to wait for 6.4.1
Thanks.

**Comment by RafaelLinux** [comment]
Not Kubuntu, but openSUSE Tumbleweed (with Plasma):

`Gtk-Message: 09:35:38.925: Failed to load module "colorreload-gtk-module"
Gtk-Message: 09:35:38.925: Failed to load module "window-decorations-gtk-module"
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-Q1VYUr/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-Q1VYUr/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-Q1VYUr/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 5094
INFO: Language detected : es_ES.UTF-8, forcing to en_US.UTF-8
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-Q1VYUr/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-Q1VYUr/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
Argument "" isn't numeric in addition (+) at /tmp/.mount_asbru-Q1VYUr/opt/asbru-cm/asbru-cm line 252.
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-Q1VYUr/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
Argument "" isn't numeric in addition (+) at /tmp/.mount_asbru-Q1VYUr/opt/asbru-cm/asbru-cm line 252.
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-Q1VYUr/usr/lib/libncursesw.so.6` with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
Argument "" isn't numeric in addition (+) at /tmp/.mount_asbru-Q1VYUr/opt/asbru-cm/asbru-cm line 252.
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-Q1VYUr/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
Argument "" isn't numeric in addition (+) at /tmp/.mount_asbru-Q1VYUr/opt/asbru-cm/asbru-cm line 252.
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: /tmp/.mount_asbru-Q1VYUr/usr/lib/libreadline.so.8: no version information available (required by sh)
sh: Relink `/tmp/.mount_asbru-Q1VYUr/usr/lib/libncursesw.so.6' with `/lib64/libc.so.6' for IFUNC symbol `strcpy'
Argument "" isn't numeric in addition (+) at /tmp/.mount_asbru-Q1VYUr/opt/asbru-cm/asbru-cm line 252.
INFO: Desktop environment detected : other
INFO: Config directory is '/home/user/.config/asbru'
Can't get tcp echo port by name at /tmp/.mount_asbru-Q1VYUr/opt/asbru-cm/lib/PACMain.pm line 173.`

Curious info about output:
Line `/tmp/.mount_asbru-Q1VYUr/usr/lib/libncursesw.so.6' ends with apostrophe (I changed it here to avoid to be interpreted as a code block) instead of "`" character.

Environment:
Operating System: openSUSE Tumbleweed 20230301
KDE Plasma Version: 5.27.1
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-1-default (64-bit)
Graphics Platform: X11

**Comment by RafaelLinux** [comment]
Additional note: In several of the output lines, sometimes begin with a open character and closes with a distinct one.

**Comment by Cris70** [comment]
Same as @RafaelLinux : openSuse Tumbleweed (with KDE Plasma), AsbruCM appimage 6.4.0 not starting.

**Comment by cebas** [comment]
I have new information to add:
Now I'm on Kubuntu 23.04. I tried to run the appimage and have the same results:
```
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 995081
INFO: Language detected : en_US.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : other
INFO: Config directory is '/home/cebas/.config/asbru'
INFO: Used config file '/home/cebas/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.62
INFO: Theme directory is '/tmp/.mount_asbru-xuA3qP/opt/asbru-cm/res/themes/default'
INFO: Trying to loading Unity specific tray icon package...
WARNING **: Failed to load shared library 'libappindicator3.so.1' referenced by the typelib: Error loading shared library libappindicator3.so.1: No such file or directory at /tmp/.mount_asbru-xuA3qP/usr/local/lib/perl5/site_perl/Glib/Object/Introspection.pm line 110.
INFO: Using Unity tray icon

```

After checking my installed packages realted to appindicator I've found this one: gir1.2-appindicator3-0.1
As no other package depends on it, I purge it. Now the asbru appimage is running fine!

```
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 996190
INFO: Language detected : en_US.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : other
INFO: Config directory is '/home/cebas/.config/asbru'
INFO: Used config file '/home/cebas/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.62
INFO: Theme directory is '/tmp/.mount_asbru-QS5unz/opt/asbru-cm/res/themes/default'
INFO: Trying to loading Unity specific tray icon package...
WARNING: AppIndicator is missing --> there might be no icon showing up in the status bar when running Unity!
INFO: Using Gnome tray icon

```

I also tried to reinstall that package to verify that the appimage fails to start.

So, my guess is that the presence of that package is confusing somebody and asbru tries to indirectly load libappindicator3.so.1.

Hope this helps!

**Comment by KarelWintersky** [comment]
Same issue, Arch Linux with KDE6
